/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
export type PostApiJobsBodyOne = {
  /**
   * @minLength 1
   * @maxLength 2048
   */
  url: string;
  /**
   * @minLength 1
   * @maxLength 64
   */
  userId: string;
};

export type PostApiJobsBodyTwo = {
  /**
   * @minLength 1
   * @maxLength 2048
   */
  url: string;
  /**
   * @minLength 1
   * @maxLength 64
   */
  userId: string;
};

export type PostApiJobsBodyThree = {
  /**
   * @minLength 1
   * @maxLength 2048
   */
  url: string;
  /**
   * @minLength 1
   * @maxLength 64
   */
  userId: string;
};

export type postApiJobsResponseDefault = {
  data: unknown;
  status: number;
};

export type postApiJobsResponseError = postApiJobsResponseDefault & {
  headers: Headers;
};

export type postApiJobsResponse = postApiJobsResponseError;

export const getPostApiJobsUrl = () => {
  return `/api/jobs`;
};

export const postApiJobs = async (
  postApiJobsBody:
    PostApiJobsBodyOne | PostApiJobsBodyTwo | PostApiJobsBodyThree,
  options?: RequestInit,
): Promise<postApiJobsResponse> => {
  const res = await fetch(getPostApiJobsUrl(), {
    ...options,
    method: "POST",
    body: JSON.stringify(postApiJobsBody),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postApiJobsResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as postApiJobsResponse;
};

export type getApiJobsByIdResponseDefault = {
  data: unknown;
  status: number;
};

export type getApiJobsByIdResponseError = getApiJobsByIdResponseDefault & {
  headers: Headers;
};

export type getApiJobsByIdResponse = getApiJobsByIdResponseError;

export const getGetApiJobsByIdUrl = (id: string) => {
  return `/api/jobs/${id}`;
};

export const getApiJobsById = async (
  id: string,
  options?: RequestInit,
): Promise<getApiJobsByIdResponse> => {
  const res = await fetch(getGetApiJobsByIdUrl(id), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApiJobsByIdResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getApiJobsByIdResponse;
};

export type getApiHealthResponseDefault = {
  data: unknown;
  status: number;
};

export type getApiHealthResponseError = getApiHealthResponseDefault & {
  headers: Headers;
};

export type getApiHealthResponse = getApiHealthResponseError;

export const getGetApiHealthUrl = () => {
  return `/api/health`;
};

export const getApiHealth = async (
  options?: RequestInit,
): Promise<getApiHealthResponse> => {
  const res = await fetch(getGetApiHealthUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApiHealthResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getApiHealthResponse;
};

export type postV1ChatCompletionsResponseDefault = {
  data: unknown;
  status: number;
};

export type postV1ChatCompletionsResponseError =
  postV1ChatCompletionsResponseDefault & {
    headers: Headers;
  };

export type postV1ChatCompletionsResponse = postV1ChatCompletionsResponseError;

export const getPostV1ChatCompletionsUrl = () => {
  return `/v1/chat/completions`;
};

export const postV1ChatCompletions = async (
  options?: RequestInit,
): Promise<postV1ChatCompletionsResponse> => {
  const res = await fetch(getPostV1ChatCompletionsUrl(), {
    ...options,
    method: "POST",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postV1ChatCompletionsResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as postV1ChatCompletionsResponse;
};

export type postChatCompletionsResponseDefault = {
  data: unknown;
  status: number;
};

export type postChatCompletionsResponseError =
  postChatCompletionsResponseDefault & {
    headers: Headers;
  };

export type postChatCompletionsResponse = postChatCompletionsResponseError;

export const getPostChatCompletionsUrl = () => {
  return `/chat/completions`;
};

export const postChatCompletions = async (
  options?: RequestInit,
): Promise<postChatCompletionsResponse> => {
  const res = await fetch(getPostChatCompletionsUrl(), {
    ...options,
    method: "POST",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postChatCompletionsResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as postChatCompletionsResponse;
};

export type getV1ModelsResponseDefault = {
  data: unknown;
  status: number;
};

export type getV1ModelsResponseError = getV1ModelsResponseDefault & {
  headers: Headers;
};

export type getV1ModelsResponse = getV1ModelsResponseError;

export const getGetV1ModelsUrl = () => {
  return `/v1/models`;
};

export const getV1Models = async (
  options?: RequestInit,
): Promise<getV1ModelsResponse> => {
  const res = await fetch(getGetV1ModelsUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getV1ModelsResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getV1ModelsResponse;
};

export type getApiDebugLastResponseDefault = {
  data: unknown;
  status: number;
};

export type getApiDebugLastResponseError = getApiDebugLastResponseDefault & {
  headers: Headers;
};

export type getApiDebugLastResponse = getApiDebugLastResponseError;

export const getGetApiDebugLastUrl = () => {
  return `/api/debug/last`;
};

export const getApiDebugLast = async (
  options?: RequestInit,
): Promise<getApiDebugLastResponse> => {
  const res = await fetch(getGetApiDebugLastUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApiDebugLastResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getApiDebugLastResponse;
};
