/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
export type PostApiJobsBodyOne = {
  /**
   * @minLength 1
   * @maxLength 2048
   */
  url: string;
  /**
   * @minLength 1
   * @maxLength 64
   */
  userId: string;
};

export type PostApiJobsBodyTwo = {
  /**
   * @minLength 1
   * @maxLength 2048
   */
  url: string;
  /**
   * @minLength 1
   * @maxLength 64
   */
  userId: string;
};

export type PostApiJobsBodyThree = {
  /**
   * @minLength 1
   * @maxLength 2048
   */
  url: string;
  /**
   * @minLength 1
   * @maxLength 64
   */
  userId: string;
};

export type postApiJobsResponseDefault = {
  data: unknown;
  status: number;
};

export type postApiJobsResponseError = postApiJobsResponseDefault & {
  headers: Headers;
};

export type postApiJobsResponse = postApiJobsResponseError;

export const getPostApiJobsUrl = () => {
  return `/api/jobs`;
};

export const postApiJobs = async (
  postApiJobsBody:
    PostApiJobsBodyOne | PostApiJobsBodyTwo | PostApiJobsBodyThree,
  options?: RequestInit,
): Promise<postApiJobsResponse> => {
  const res = await fetch(getPostApiJobsUrl(), {
    ...options,
    method: "POST",
    body: JSON.stringify(postApiJobsBody),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postApiJobsResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as postApiJobsResponse;
};

export type getApiJobsByIdResponseDefault = {
  data: unknown;
  status: number;
};

export type getApiJobsByIdResponseError = getApiJobsByIdResponseDefault & {
  headers: Headers;
};

export type getApiJobsByIdResponse = getApiJobsByIdResponseError;

export const getGetApiJobsByIdUrl = (id: string) => {
  return `/api/jobs/${id}`;
};

export const getApiJobsById = async (
  id: string,
  options?: RequestInit,
): Promise<getApiJobsByIdResponse> => {
  const res = await fetch(getGetApiJobsByIdUrl(id), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApiJobsByIdResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getApiJobsByIdResponse;
};

export type getApiHealthResponseDefault = {
  data: unknown;
  status: number;
};

export type getApiHealthResponseError = getApiHealthResponseDefault & {
  headers: Headers;
};

export type getApiHealthResponse = getApiHealthResponseError;

export const getGetApiHealthUrl = () => {
  return `/api/health`;
};

export const getApiHealth = async (
  options?: RequestInit,
): Promise<getApiHealthResponse> => {
  const res = await fetch(getGetApiHealthUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApiHealthResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getApiHealthResponse;
};

export type postApiDebugEchoResponseDefault = {
  data: unknown;
  status: number;
};

export type postApiDebugEchoResponseError = postApiDebugEchoResponseDefault & {
  headers: Headers;
};

export type postApiDebugEchoResponse = postApiDebugEchoResponseError;

export const getPostApiDebugEchoUrl = () => {
  return `/api/debug/echo`;
};

export const postApiDebugEcho = async (
  options?: RequestInit,
): Promise<postApiDebugEchoResponse> => {
  const res = await fetch(getPostApiDebugEchoUrl(), {
    ...options,
    method: "POST",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postApiDebugEchoResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as postApiDebugEchoResponse;
};

export type getApiDebugLastResponseDefault = {
  data: unknown;
  status: number;
};

export type getApiDebugLastResponseError = getApiDebugLastResponseDefault & {
  headers: Headers;
};

export type getApiDebugLastResponse = getApiDebugLastResponseError;

export const getGetApiDebugLastUrl = () => {
  return `/api/debug/last`;
};

export const getApiDebugLast = async (
  options?: RequestInit,
): Promise<getApiDebugLastResponse> => {
  const res = await fetch(getGetApiDebugLastUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApiDebugLastResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getApiDebugLastResponse;
};
