/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import { unoImportFetch } from "./uno-import-fetch";
export type PostApiJobsBodyOne = {
  /**
   * @minLength 1
   * @maxLength 2048
   */
  url: string;
  /**
   * @minLength 1
   * @maxLength 64
   */
  userId: string;
};

export type PostApiJobsBodyTwo = {
  /**
   * @minLength 1
   * @maxLength 2048
   */
  url: string;
  /**
   * @minLength 1
   * @maxLength 64
   */
  userId: string;
};

export type PostApiJobsBodyThree = {
  /**
   * @minLength 1
   * @maxLength 2048
   */
  url: string;
  /**
   * @minLength 1
   * @maxLength 64
   */
  userId: string;
};

export type PostApiJobs200 = {
  jobId: string;
  status: string;
};

export type PostApiJobs400AnyOf = {
  error: "invalid url";
};

export type PostApiJobs400AnyOfTwo = {
  error: "https only";
};

export type PostApiJobs400AnyOfThree = {
  error: "unsupported source";
};

export type PostApiJobs400 =
  PostApiJobs400AnyOf | PostApiJobs400AnyOfTwo | PostApiJobs400AnyOfThree;

export type PostApiJobs422 = {
  type: "validation";
  on: string;
  summary?: string;
  message?: string;
  found?: unknown;
  property?: string;
  expected?: string;
};

export type PostApiJobs429 = {
  error: "too many jobs in flight";
};

export type GetApiJobsById200ResultAnyOfAvatar = {
  name: string;
  mimeType: string;
  base64: string;
};

export type GetApiJobsById200ResultAnyOfCardData = { [key: string]: unknown };

export type GetApiJobsById200ResultAnyOfCard = {
  spec: string;
  spec_version?: string;
  data: GetApiJobsById200ResultAnyOfCardData;
};

export type GetApiJobsById200ResultAnyOfLorebooksItemEntriesItemInjectionRole =
  "system" | "user" | "assistant";

export type GetApiJobsById200ResultAnyOfLorebooksItemEntriesItem = {
  keys: string[];
  secondaryKeys?: string[];
  content: string;
  comment?: string;
  enabled: boolean;
  constant: boolean;
  selective: boolean;
  priority: number;
  orderIndex: number;
  matchWholeWords: boolean;
  injectionRole?: GetApiJobsById200ResultAnyOfLorebooksItemEntriesItemInjectionRole;
  chance?: number;
};

export type GetApiJobsById200ResultAnyOfLorebooksItem = {
  name: string;
  scanDepth?: number;
  entries: GetApiJobsById200ResultAnyOfLorebooksItemEntriesItem[];
};

export type GetApiJobsById200ResultAnyOfSkippedItemReason =
  "private" | "not_found";

export type GetApiJobsById200ResultAnyOfSkippedItem = {
  title: string;
  reason: GetApiJobsById200ResultAnyOfSkippedItemReason;
};

export type GetApiJobsById200ResultAnyOf = {
  kind?: "character";
  source: string;
  sourceUrl: string;
  avatar?: GetApiJobsById200ResultAnyOfAvatar;
  card: GetApiJobsById200ResultAnyOfCard;
  lorebooks: GetApiJobsById200ResultAnyOfLorebooksItem[];
  skipped: GetApiJobsById200ResultAnyOfSkippedItem[];
};

export type GetApiJobsById200ResultAnyOfOnezeroLorebooksItemEntriesItemInjectionRole =
  "system" | "user" | "assistant";

export type GetApiJobsById200ResultAnyOfOnezeroLorebooksItemEntriesItem = {
  keys: string[];
  secondaryKeys?: string[];
  content: string;
  comment?: string;
  enabled: boolean;
  constant: boolean;
  selective: boolean;
  priority: number;
  orderIndex: number;
  matchWholeWords: boolean;
  injectionRole?: GetApiJobsById200ResultAnyOfOnezeroLorebooksItemEntriesItemInjectionRole;
  chance?: number;
};

export type GetApiJobsById200ResultAnyOfOnezeroLorebooksItem = {
  name: string;
  scanDepth?: number;
  entries: GetApiJobsById200ResultAnyOfOnezeroLorebooksItemEntriesItem[];
};

export type GetApiJobsById200ResultAnyOfOnezeroSkippedItemReason =
  "private" | "not_found";

export type GetApiJobsById200ResultAnyOfOnezeroSkippedItem = {
  title: string;
  reason: GetApiJobsById200ResultAnyOfOnezeroSkippedItemReason;
};

export type GetApiJobsById200ResultAnyOfOnezero = {
  kind: "lorebook";
  source: string;
  sourceUrl: string;
  lorebooks: GetApiJobsById200ResultAnyOfOnezeroLorebooksItem[];
  skipped: GetApiJobsById200ResultAnyOfOnezeroSkippedItem[];
};

export type GetApiJobsById200ResultAnyOfOnesixPersonasItemAttributes = {
  [key: string]: unknown;
};

export type GetApiJobsById200ResultAnyOfOnesixPersonasItem = {
  name: string;
  description: string;
  attributes?: GetApiJobsById200ResultAnyOfOnesixPersonasItemAttributes;
};

export type GetApiJobsById200ResultAnyOfOnesix = {
  kind: "persona";
  source: string;
  sourceUrl: string;
  personas: GetApiJobsById200ResultAnyOfOnesixPersonasItem[];
};

export type GetApiJobsById200ResultAnyOfOneninePlugin = {
  name: string;
  script: string;
};

export type GetApiJobsById200ResultAnyOfOnenine = {
  kind: "plugin";
  source: string;
  sourceUrl: string;
  plugin: GetApiJobsById200ResultAnyOfOneninePlugin;
};

export type GetApiJobsById200ResultAnyOfTwoonePreset = {
  name: string;
  promptTemplate: string;
};

export type GetApiJobsById200ResultAnyOfTwooneLorebooksItemEntriesItemInjectionRole =
  "system" | "user" | "assistant";

export type GetApiJobsById200ResultAnyOfTwooneLorebooksItemEntriesItem = {
  keys: string[];
  secondaryKeys?: string[];
  content: string;
  comment?: string;
  enabled: boolean;
  constant: boolean;
  selective: boolean;
  priority: number;
  orderIndex: number;
  matchWholeWords: boolean;
  injectionRole?: GetApiJobsById200ResultAnyOfTwooneLorebooksItemEntriesItemInjectionRole;
  chance?: number;
};

export type GetApiJobsById200ResultAnyOfTwooneLorebooksItem = {
  name: string;
  scanDepth?: number;
  entries: GetApiJobsById200ResultAnyOfTwooneLorebooksItemEntriesItem[];
};

export type GetApiJobsById200ResultAnyOfTwoone = {
  kind: "preset";
  source: string;
  sourceUrl: string;
  preset: GetApiJobsById200ResultAnyOfTwoonePreset;
  lorebooks: GetApiJobsById200ResultAnyOfTwooneLorebooksItem[];
};

export type GetApiJobsById200ResultAnyOfTwosixAvatar = {
  name: string;
  mimeType: string;
  base64: string;
};

export type GetApiJobsById200ResultAnyOfTwosixCardData = {
  [key: string]: unknown;
};

export type GetApiJobsById200ResultAnyOfTwosixCard = {
  spec: string;
  spec_version?: string;
  data: GetApiJobsById200ResultAnyOfTwosixCardData;
};

export type GetApiJobsById200ResultAnyOfTwosixLorebooksItemEntriesItemInjectionRole =
  "system" | "user" | "assistant";

export type GetApiJobsById200ResultAnyOfTwosixLorebooksItemEntriesItem = {
  keys: string[];
  secondaryKeys?: string[];
  content: string;
  comment?: string;
  enabled: boolean;
  constant: boolean;
  selective: boolean;
  priority: number;
  orderIndex: number;
  matchWholeWords: boolean;
  injectionRole?: GetApiJobsById200ResultAnyOfTwosixLorebooksItemEntriesItemInjectionRole;
  chance?: number;
};

export type GetApiJobsById200ResultAnyOfTwosixLorebooksItem = {
  name: string;
  scanDepth?: number;
  entries: GetApiJobsById200ResultAnyOfTwosixLorebooksItemEntriesItem[];
};

export type GetApiJobsById200ResultAnyOfTwosixAssetsItem = {
  name: string;
  mimeType: string;
  base64: string;
};

export type GetApiJobsById200ResultAnyOfTwosix = {
  kind: "rich-character";
  source: string;
  sourceUrl: string;
  avatar?: GetApiJobsById200ResultAnyOfTwosixAvatar;
  card: GetApiJobsById200ResultAnyOfTwosixCard;
  lorebooks: GetApiJobsById200ResultAnyOfTwosixLorebooksItem[];
  regexScripts?: unknown;
  triggers?: unknown;
  assets: GetApiJobsById200ResultAnyOfTwosixAssetsItem[];
};

export type GetApiJobsById200Result =
  | GetApiJobsById200ResultAnyOf
  | GetApiJobsById200ResultAnyOfOnezero
  | GetApiJobsById200ResultAnyOfOnesix
  | GetApiJobsById200ResultAnyOfOnenine
  | GetApiJobsById200ResultAnyOfTwoone
  | GetApiJobsById200ResultAnyOfTwosix
  | null;

export type GetApiJobsById200Error = string | null;

export type GetApiJobsById200 = {
  status: string;
  result: GetApiJobsById200Result;
  error: GetApiJobsById200Error;
};

export type GetApiJobsById404 = {
  error: "not found";
};

export type GetApiJobsById422 = {
  type: "validation";
  on: string;
  summary?: string;
  message?: string;
  found?: unknown;
  property?: string;
  expected?: string;
};

export type GetApiHealth200 = {
  ok: boolean;
  exitUsable: boolean;
  exitIp: string;
  queueDepth: number;
};

export type PostV1ChatCompletions200ChoicesItemMessage = {
  role: string;
  content: string;
};

export type PostV1ChatCompletions200ChoicesItem = {
  index: number;
  message: PostV1ChatCompletions200ChoicesItemMessage;
  finish_reason: string;
};

export type PostV1ChatCompletions200Usage = {
  prompt_tokens: number;
  completion_tokens: number;
  total_tokens: number;
};

export type PostV1ChatCompletions200 = {
  id: string;
  object: string;
  created: number;
  model: string;
  choices: PostV1ChatCompletions200ChoicesItem[];
  usage: PostV1ChatCompletions200Usage;
};

export type PostV1ChatCompletions422 = {
  type: "validation";
  on: string;
  summary?: string;
  message?: string;
  found?: unknown;
  property?: string;
  expected?: string;
};

export type PostChatCompletions200ChoicesItemMessage = {
  role: string;
  content: string;
};

export type PostChatCompletions200ChoicesItem = {
  index: number;
  message: PostChatCompletions200ChoicesItemMessage;
  finish_reason: string;
};

export type PostChatCompletions200Usage = {
  prompt_tokens: number;
  completion_tokens: number;
  total_tokens: number;
};

export type PostChatCompletions200 = {
  id: string;
  object: string;
  created: number;
  model: string;
  choices: PostChatCompletions200ChoicesItem[];
  usage: PostChatCompletions200Usage;
};

export type PostChatCompletions422 = {
  type: "validation";
  on: string;
  summary?: string;
  message?: string;
  found?: unknown;
  property?: string;
  expected?: string;
};

export type GetV1Models200DataItem = {
  id: string;
  object: string;
  owned_by: string;
};

export type GetV1Models200 = {
  object: string;
  data: GetV1Models200DataItem[];
};

export type GetV1Models422 = {
  type: "validation";
  on: string;
  summary?: string;
  message?: string;
  found?: unknown;
  property?: string;
  expected?: string;
};

export type GetApiDebugLast200CapturedItemHeaders = { [key: string]: unknown };

export type GetApiDebugLast200CapturedItemMessagesItem = {
  role: unknown;
  chars: number;
  preview: string;
};

export type GetApiDebugLast200CapturedItem = {
  at: string;
  path: string;
  headers: GetApiDebugLast200CapturedItemHeaders;
  model: unknown;
  messages: GetApiDebugLast200CapturedItemMessagesItem[];
};

export type GetApiDebugLast200 = {
  count: number;
  captured: GetApiDebugLast200CapturedItem[];
};

export type GetApiDebugLast422 = {
  type: "validation";
  on: string;
  summary?: string;
  message?: string;
  found?: unknown;
  property?: string;
  expected?: string;
};

export type postApiJobsResponse200 = {
  data: PostApiJobs200;
  status: 200;
};

export type postApiJobsResponse400 = {
  data: PostApiJobs400;
  status: 400;
};

export type postApiJobsResponse422 = {
  data: PostApiJobs422;
  status: 422;
};

export type postApiJobsResponse429 = {
  data: PostApiJobs429;
  status: 429;
};

export type postApiJobsResponseSuccess = postApiJobsResponse200 & {
  headers: Headers;
};
export type postApiJobsResponseError = (
  postApiJobsResponse400 | postApiJobsResponse422 | postApiJobsResponse429
) & {
  headers: Headers;
};

export type postApiJobsResponse =
  postApiJobsResponseSuccess | postApiJobsResponseError;

export const getPostApiJobsUrl = () => {
  return `/api/jobs`;
};

export const postApiJobs = async (
  postApiJobsBody:
    PostApiJobsBodyOne | PostApiJobsBodyTwo | PostApiJobsBodyThree,
  options?: Parameters<typeof unoImportFetch>[1],
): Promise<postApiJobsResponse> => {
  return unoImportFetch<postApiJobsResponse>(getPostApiJobsUrl(), {
    ...options,
    method: "POST",
    body: JSON.stringify(postApiJobsBody),
  });
};

export type getApiJobsByIdResponse200 = {
  data: GetApiJobsById200;
  status: 200;
};

export type getApiJobsByIdResponse404 = {
  data: GetApiJobsById404;
  status: 404;
};

export type getApiJobsByIdResponse422 = {
  data: GetApiJobsById422;
  status: 422;
};

export type getApiJobsByIdResponseSuccess = getApiJobsByIdResponse200 & {
  headers: Headers;
};
export type getApiJobsByIdResponseError = (
  getApiJobsByIdResponse404 | getApiJobsByIdResponse422
) & {
  headers: Headers;
};

export type getApiJobsByIdResponse =
  getApiJobsByIdResponseSuccess | getApiJobsByIdResponseError;

export const getGetApiJobsByIdUrl = (id: string) => {
  return `/api/jobs/${id}`;
};

export const getApiJobsById = async (
  id: string,
  options?: Parameters<typeof unoImportFetch>[1],
): Promise<getApiJobsByIdResponse> => {
  return unoImportFetch<getApiJobsByIdResponse>(getGetApiJobsByIdUrl(id), {
    ...options,
    method: "GET",
  });
};

export type getApiHealthResponse200 = {
  data: GetApiHealth200;
  status: 200;
};

export type getApiHealthResponseSuccess = getApiHealthResponse200 & {
  headers: Headers;
};
export type getApiHealthResponse = getApiHealthResponseSuccess;

export const getGetApiHealthUrl = () => {
  return `/api/health`;
};

export const getApiHealth = async (
  options?: Parameters<typeof unoImportFetch>[1],
): Promise<getApiHealthResponse> => {
  return unoImportFetch<getApiHealthResponse>(getGetApiHealthUrl(), {
    ...options,
    method: "GET",
  });
};

export type postV1ChatCompletionsResponse200 = {
  data: PostV1ChatCompletions200;
  status: 200;
};

export type postV1ChatCompletionsResponse404 = {
  data: "Not Found";
  status: 404;
};

export type postV1ChatCompletionsResponse422 = {
  data: PostV1ChatCompletions422;
  status: 422;
};

export type postV1ChatCompletionsResponseSuccess =
  postV1ChatCompletionsResponse200 & {
    headers: Headers;
  };
export type postV1ChatCompletionsResponseError = (
  postV1ChatCompletionsResponse404 | postV1ChatCompletionsResponse422
) & {
  headers: Headers;
};

export type postV1ChatCompletionsResponse =
  postV1ChatCompletionsResponseSuccess | postV1ChatCompletionsResponseError;

export const getPostV1ChatCompletionsUrl = () => {
  return `/v1/chat/completions`;
};

export const postV1ChatCompletions = async (
  options?: Parameters<typeof unoImportFetch>[1],
): Promise<postV1ChatCompletionsResponse> => {
  return unoImportFetch<postV1ChatCompletionsResponse>(
    getPostV1ChatCompletionsUrl(),
    {
      ...options,
      method: "POST",
    },
  );
};

export type postChatCompletionsResponse200 = {
  data: PostChatCompletions200;
  status: 200;
};

export type postChatCompletionsResponse404 = {
  data: "Not Found";
  status: 404;
};

export type postChatCompletionsResponse422 = {
  data: PostChatCompletions422;
  status: 422;
};

export type postChatCompletionsResponseSuccess =
  postChatCompletionsResponse200 & {
    headers: Headers;
  };
export type postChatCompletionsResponseError = (
  postChatCompletionsResponse404 | postChatCompletionsResponse422
) & {
  headers: Headers;
};

export type postChatCompletionsResponse =
  postChatCompletionsResponseSuccess | postChatCompletionsResponseError;

export const getPostChatCompletionsUrl = () => {
  return `/chat/completions`;
};

export const postChatCompletions = async (
  options?: Parameters<typeof unoImportFetch>[1],
): Promise<postChatCompletionsResponse> => {
  return unoImportFetch<postChatCompletionsResponse>(
    getPostChatCompletionsUrl(),
    {
      ...options,
      method: "POST",
    },
  );
};

export type getV1ModelsResponse200 = {
  data: GetV1Models200;
  status: 200;
};

export type getV1ModelsResponse404 = {
  data: "Not Found";
  status: 404;
};

export type getV1ModelsResponse422 = {
  data: GetV1Models422;
  status: 422;
};

export type getV1ModelsResponseSuccess = getV1ModelsResponse200 & {
  headers: Headers;
};
export type getV1ModelsResponseError = (
  getV1ModelsResponse404 | getV1ModelsResponse422
) & {
  headers: Headers;
};

export type getV1ModelsResponse =
  getV1ModelsResponseSuccess | getV1ModelsResponseError;

export const getGetV1ModelsUrl = () => {
  return `/v1/models`;
};

export const getV1Models = async (
  options?: Parameters<typeof unoImportFetch>[1],
): Promise<getV1ModelsResponse> => {
  return unoImportFetch<getV1ModelsResponse>(getGetV1ModelsUrl(), {
    ...options,
    method: "GET",
  });
};

export type getApiDebugLastResponse200 = {
  data: GetApiDebugLast200;
  status: 200;
};

export type getApiDebugLastResponse404 = {
  data: "Not Found";
  status: 404;
};

export type getApiDebugLastResponse422 = {
  data: GetApiDebugLast422;
  status: 422;
};

export type getApiDebugLastResponseSuccess = getApiDebugLastResponse200 & {
  headers: Headers;
};
export type getApiDebugLastResponseError = (
  getApiDebugLastResponse404 | getApiDebugLastResponse422
) & {
  headers: Headers;
};

export type getApiDebugLastResponse =
  getApiDebugLastResponseSuccess | getApiDebugLastResponseError;

export const getGetApiDebugLastUrl = () => {
  return `/api/debug/last`;
};

export const getApiDebugLast = async (
  options?: Parameters<typeof unoImportFetch>[1],
): Promise<getApiDebugLastResponse> => {
  return unoImportFetch<getApiDebugLastResponse>(getGetApiDebugLastUrl(), {
    ...options,
    method: "GET",
  });
};
