import { withPostHogConfig } from "@posthog/nextjs-config";
import type { NextConfig } from "next";
import createNextIntlPlugin from "next-intl/plugin";

const nextConfig: NextConfig = {
  output: process.env.STANDALONE ? "standalone" : undefined,
  // SQLocal's webpack/Turbopack worker bundling is broken (turbopack issue
  // #79 + webpack injects `importScripts` chunk loader incompatible with
  // module workers). We patch SQLocal to load a prebundled worker from
  // /public/sqlocal-worker.mjs instead. `transpilePackages` no longer needed
  // for SQLocal, but @sqlite.org/sqlite-wasm pulled in via the patched
  // client.ts on the main thread (e.g. `import("@sqlite.org/sqlite-wasm")`
  // happens only inside the worker now).
  transpilePackages: ["sqlocal"],
  // productionBrowserSourceMaps: true,
  // experimental: {
  //   allowDevelopmentBuild: true,
  // },
  images: {
    formats: ["image/webp"],
    qualities: [10, 25, 50, 75, 90, 100],
    minimumCacheTTL: 60 * 60 * 24,
  },
  // Cross-origin isolation for OPFS sync access handles used by SQLocal
  // on the chat + generate route groups. Required for SQLite WASM to
  // persist its DB file across reloads. Marketing pages are untouched.
  async headers() {
    return [
      {
        source: "/:locale/chat/:path*",
        headers: [
          { key: "Cross-Origin-Embedder-Policy", value: "require-corp" },
          { key: "Cross-Origin-Opener-Policy", value: "same-origin" },
        ],
      },
      {
        source: "/:locale/generate/:path*",
        headers: [
          { key: "Cross-Origin-Embedder-Policy", value: "require-corp" },
          { key: "Cross-Origin-Opener-Policy", value: "same-origin" },
        ],
      },
      // The SQLocal worker dynamically imports turbopack chunks from
      // /_next/static/. COEP `require-corp` on the page blocks any
      // sub-resource without `Cross-Origin-Resource-Policy: same-origin`.
      // Stamp CORP on every static chunk so the worker can load them.
      {
        source: "/_next/static/:path*",
        headers: [
          { key: "Cross-Origin-Resource-Policy", value: "same-origin" },
        ],
      },
      // Same fix for /api/ - the OPFS-isolated page reads its own BFF
      // routes via fetch; without CORP those responses get COEP-blocked.
      {
        source: "/api/:path*",
        headers: [
          { key: "Cross-Origin-Resource-Policy", value: "same-origin" },
        ],
      },
      // Prebundled SQLocal worker + sqlite-wasm siblings live under
      // /public/sqlocal (generated by scripts/bundle-sqlocal-worker.ts).
      // COEP-isolated chat page can only spawn workers whose scripts carry
      // COEP themselves, and any sub-resources need CORP same-origin.
      {
        source: "/sqlocal/:path*",
        headers: [
          { key: "Cross-Origin-Embedder-Policy", value: "require-corp" },
          { key: "Cross-Origin-Opener-Policy", value: "same-origin" },
          { key: "Cross-Origin-Resource-Policy", value: "same-origin" },
        ],
      },
    ];
  },
};

const withNextIntl = createNextIntlPlugin({
  experimental: {
    createMessagesDeclaration: ["./public/i18n/de.json"],
  },
});

const configWithNextIntl = withNextIntl(nextConfig);

export default process.env.STANDALONE
  ? withPostHogConfig(configWithNextIntl, {
      personalApiKey: process.env.POSTHOG_API_KEY!,
      envId: process.env.POSTHOG_ENV_ID!,
      host: "https://eu.i.posthog.com",
      sourcemaps: {
        enabled: true,
        project: process.env.NEXT_PUBLIC_APP_NAME,
        version: "1.0.0",
        deleteAfterUpload: true,
      },
    })
  : configWithNextIntl;
