import { GUEST_USER_ID } from "@/lib/config/constants";
import { jotaiCookieStorage } from "@/lib/config/table-storage";
import type { StreamOverrides } from "@/lib/validation/chat";
import { uid } from "@/lib/utils/base";
import { atom, createStore } from "jotai";
import { atomWithStorage } from "jotai/utils";

export const CHAT_STORE_KEY = "chat-store";

export type ModelSamplerMemory = Pick<
  StreamOverrides,
  | "temperature"
  | "topP"
  | "topK"
  | "minP"
  | "topA"
  | "frequencyPenalty"
  | "presencePenalty"
  | "repetitionPenalty"
  | "maxTokens"
  | "reasoningEffort"
  | "extraBody"
>;

// Sticky RP loadout auto-equipped on every new chat; seeded by the thread-list
// adapter's initialize().
export type ChatLoadout = {
  presetId: string | null;
  personaId: string | null;
  characterIds: string[];
  lorebookIds: string[];
};

const EMPTY_LOADOUT: ChatLoadout = {
  presetId: null,
  personaId: null,
  characterIds: [],
  lorebookIds: [],
};

export type ChatState = {
  model: string | null;
  // Default billing/routing group seeding new chats; null = auto.
  group: string | null;
  webSearch: boolean;
  defaults: StreamOverrides;
  loadout: ChatLoadout;
  samplerMemoryByModel: Record<string, ModelSamplerMemory>;
};

export const INITIAL_CHAT_STATE: ChatState = {
  model: null,
  group: null,
  webSearch: false,
  defaults: {},
  loadout: EMPTY_LOADOUT,
  samplerMemoryByModel: {},
};

// SSR-hydrated from the cookie by ChatStoreProvider; no getOnInit needed.
export const chatStoreAtom = atomWithStorage<ChatState>(
  CHAT_STORE_KEY,
  INITIAL_CHAT_STATE,
  jotaiCookieStorage,
);

// Per-field fallback covers older cookie schema.
export const chatModelAtom = atom(
  (get) => get(chatStoreAtom).model ?? INITIAL_CHAT_STATE.model,
  (get, set, value: string | null) => {
    set(chatStoreAtom, { ...get(chatStoreAtom), model: value });
  },
);

export const chatGroupAtom = atom(
  (get) => get(chatStoreAtom).group ?? INITIAL_CHAT_STATE.group,
  (get, set, value: string | null) => {
    set(chatStoreAtom, { ...get(chatStoreAtom), group: value });
  },
);

export const chatWebSearchAtom = atom(
  (get) => get(chatStoreAtom).webSearch ?? INITIAL_CHAT_STATE.webSearch,
  (get, set, value: boolean) => {
    set(chatStoreAtom, { ...get(chatStoreAtom), webSearch: value });
  },
);

export const chatDefaultsAtom = atom(
  (get) => get(chatStoreAtom).defaults ?? INITIAL_CHAT_STATE.defaults,
  (get, set, value: StreamOverrides) => {
    set(chatStoreAtom, { ...get(chatStoreAtom), defaults: value });
  },
);

export const chatLoadoutAtom = atom(
  (get) => get(chatStoreAtom).loadout ?? INITIAL_CHAT_STATE.loadout,
  (get, set, value: ChatLoadout) => {
    set(chatStoreAtom, { ...get(chatStoreAtom), loadout: value });
  },
);

export const samplerMemoryByModelAtom = atom(
  (get) =>
    get(chatStoreAtom).samplerMemoryByModel ??
    INITIAL_CHAT_STATE.samplerMemoryByModel,
  (get, set, value: Record<string, ModelSamplerMemory>) => {
    set(chatStoreAtom, { ...get(chatStoreAtom), samplerMemoryByModel: value });
  },
);

export type ChatHelpersRef = {
  setMessages: (updater: (msgs: unknown[]) => unknown[]) => void;
  getMessages: () => ReadonlyArray<unknown>;
  sendEmpty: () => Promise<void>;
};

// In-memory runtime state, NEVER persisted (per-tab, per-stream). Object-backed
// like the main ChatState so it's one source with derived per-field atoms, but
// a plain atom (no storage) since none of it should survive reload or ride a
// cookie. Helper refs / globalVars (localStorage) / localUserId (provider-seeded)
// stay separate below: each needs a storage tier this object can't give.
export type ChatRuntimeState = {
  // Active stream convId; generated by ensureConvId, mirrored from the thread.
  convId: string | null;
  // True once the history adapter's first load() resolved; the thread welcome
  // waits on it so a conv URL shows a skeleton instead of flashing the empty
  // welcome while messages load from the local DB.
  historyLoaded: boolean;
  // Conversation settings/overrides drawer open; shared so the header badge and
  // the actions menu drive the same drawer.
  settingsOpen: boolean;
  // Last stream failure; the history adapter persists the failed run as an error
  // node instead of an empty ghost branch.
  lastStreamError: { message: string; at: number } | null;
  // Speaking character for the current stream (multi-character rotation).
  speakingCharacterId: string | null;
  // Greeting picked on the empty-thread preview (0 = firstMessage, i =
  // alternateGreetings[i-1]); thread-list initialize seeds branches from it.
  greetingIndex: number;
};

const INITIAL_RUNTIME_STATE: ChatRuntimeState = {
  convId: null,
  historyLoaded: false,
  settingsOpen: false,
  lastStreamError: null,
  speakingCharacterId: null,
  greetingIndex: 0,
};

const chatRuntimeAtom = atom<ChatRuntimeState>(INITIAL_RUNTIME_STATE);

// One read/write derived atom per field; backed by chatRuntimeAtom. Call sites
// (React hooks + imperative chatStore.get/set) keep the same per-field API.
function runtimeField<K extends keyof ChatRuntimeState>(key: K) {
  return atom(
    (get) => get(chatRuntimeAtom)[key],
    (get, set, value: ChatRuntimeState[K]) => {
      set(chatRuntimeAtom, { ...get(chatRuntimeAtom), [key]: value });
    },
  );
}

export const convIdAtom = runtimeField("convId");
export const historyLoadedAtom = runtimeField("historyLoaded");
export const conversationSettingsOpenAtom = runtimeField("settingsOpen");
export const lastStreamErrorAtom = runtimeField("lastStreamError");
export const speakingCharacterIdAtom = runtimeField("speakingCharacterId");
export const greetingIndexAtom = runtimeField("greetingIndex");

export const chatHelpersAtom = atom<ChatHelpersRef | null>(null);

// Per-user global macro vars (JSON map). localStorage-backed (can outgrow the
// cookie cap); read into chatContext, updated from finish-meta writeback.
export const globalVarsAtom = atomWithStorage<string>(
  "rp-global-vars",
  "{}",
  undefined,
  { getOnInit: true },
);

// Authoritative local-DB owner (real user id, or GUEST_USER_ID). Seeded
// server-side by UserIdProvider from the sealed user-id cookie, so it is
// correct on the first client render with no auth-query race. Read via
// useLocalUserId() in React, or chatStore.get(localUserIdAtom) in the
// imperative stream/runtime callbacks.
export const localUserIdAtom = atom<number>(GUEST_USER_ID);

// Non-React stream callbacks read via chatStore.get/set.
export const chatStore = createStore();

// Returns active convId, generating fresh when unset; shared across transport/history/init.
export function ensureConvId(): string {
  const id = chatStore.get(convIdAtom) ?? uid();
  chatStore.set(convIdAtom, id);
  return id;
}
