import { GUEST_USER_ID } from "@/lib/config/constants";
import { jotaiCookieStorage } from "@/lib/config/table-storage";
import type { StreamOverrides } from "@/lib/validation/chat";
import { uid } from "@/lib/utils/base";
import { atom, createStore } from "jotai";
import { atomWithStorage } from "jotai/utils";

export const CHAT_STORE_KEY = "chat-store";

export type ModelSamplerMemory = Pick<
  StreamOverrides,
  | "temperature"
  | "topP"
  | "topK"
  | "minP"
  | "topA"
  | "frequencyPenalty"
  | "presencePenalty"
  | "repetitionPenalty"
  | "maxTokens"
  | "reasoningEffort"
  | "extraBody"
>;

    // Sticky RP loadout auto-equipped on every new chat; seeded by the thread-list adapter's initialize().
export type ChatLoadout = {
  presetId: string | null;
  personaId: string | null;
  characterIds: string[];
  lorebookIds: string[];
};

const EMPTY_LOADOUT: ChatLoadout = {
  presetId: null,
  personaId: null,
  characterIds: [],
  lorebookIds: [],
};

export type ChatState = {
  model: string | null;
  // Default billing/routing group seeding new chats; null = auto.
  group: string | null;
  webSearch: boolean;
  defaults: StreamOverrides;
  loadout: ChatLoadout;
  samplerMemoryByModel: Record<string, ModelSamplerMemory>;
  // Chat-total display prefs (global). Tokens off by default: the cumulative billed-token sum confuses users; cost is the clear signal.
  showStatsTokens: boolean;
  showStatsCost: boolean;
};

export const INITIAL_CHAT_STATE: ChatState = {
  model: null,
  group: null,
  webSearch: false,
  defaults: {},
  loadout: EMPTY_LOADOUT,
  samplerMemoryByModel: {},
  showStatsTokens: false,
  showStatsCost: true,
};

// SSR-hydrated from the cookie by ChatStoreProvider; no getOnInit needed.
export const chatStoreAtom = atomWithStorage<ChatState>(
  CHAT_STORE_KEY,
  INITIAL_CHAT_STATE,
  jotaiCookieStorage,
);

// Per-field fallback covers older cookie schema.
export const chatModelAtom = atom(
  (get) => get(chatStoreAtom).model ?? INITIAL_CHAT_STATE.model,
  (get, set, value: string | null) => {
    set(chatStoreAtom, { ...get(chatStoreAtom), model: value });
  },
);

export const chatGroupAtom = atom(
  (get) => get(chatStoreAtom).group ?? INITIAL_CHAT_STATE.group,
  (get, set, value: string | null) => {
    set(chatStoreAtom, { ...get(chatStoreAtom), group: value });
  },
);

export const chatWebSearchAtom = atom(
  (get) => get(chatStoreAtom).webSearch ?? INITIAL_CHAT_STATE.webSearch,
  (get, set, value: boolean) => {
    set(chatStoreAtom, { ...get(chatStoreAtom), webSearch: value });
  },
);

export const showStatsTokensAtom = atom(
  (get) =>
    get(chatStoreAtom).showStatsTokens ?? INITIAL_CHAT_STATE.showStatsTokens,
  (get, set, value: boolean) => {
    set(chatStoreAtom, { ...get(chatStoreAtom), showStatsTokens: value });
  },
);

export const showStatsCostAtom = atom(
  (get) => get(chatStoreAtom).showStatsCost ?? INITIAL_CHAT_STATE.showStatsCost,
  (get, set, value: boolean) => {
    set(chatStoreAtom, { ...get(chatStoreAtom), showStatsCost: value });
  },
);

export const chatDefaultsAtom = atom(
  (get) => get(chatStoreAtom).defaults ?? INITIAL_CHAT_STATE.defaults,
  (get, set, value: StreamOverrides) => {
    set(chatStoreAtom, { ...get(chatStoreAtom), defaults: value });
  },
);

export const chatLoadoutAtom = atom(
  (get) => get(chatStoreAtom).loadout ?? INITIAL_CHAT_STATE.loadout,
  (get, set, value: ChatLoadout) => {
    set(chatStoreAtom, { ...get(chatStoreAtom), loadout: value });
  },
);

export const samplerMemoryByModelAtom = atom(
  (get) =>
    get(chatStoreAtom).samplerMemoryByModel ??
    INITIAL_CHAT_STATE.samplerMemoryByModel,
  (get, set, value: Record<string, ModelSamplerMemory>) => {
    set(chatStoreAtom, { ...get(chatStoreAtom), samplerMemoryByModel: value });
  },
);

export type ChatHelpersRef = {
  setMessages: (updater: (msgs: unknown[]) => unknown[]) => void;
  getMessages: () => ReadonlyArray<unknown>;
  sendEmpty: () => Promise<void>;
};

    // In-memory per-tab runtime state, never persisted. Object-backed with derived per-field atoms, but a plain atom (no storage).
export type ChatRuntimeState = {
  // Active stream convId; generated by ensureConvId, mirrored from the thread.
  convId: string | null;
      // True once the adapter's first load() resolved; the welcome waits on it so a conv URL shows a skeleton, not a flash of empty welcome.
  historyLoaded: boolean;
      // Conversation settings drawer open; shared so the header badge and actions menu drive the same drawer.
  settingsOpen: boolean;
      // Last stream failure; the adapter persists the failed run as an error node, not an empty ghost branch. code/status/requestId carry the full upstream detail for debugging.
  lastStreamError: {
    message: string;
    at: number;
    code?: string;
    status?: number;
    requestId?: string;
  } | null;
  // Speaking character for the current stream (multi-character rotation).
  speakingCharacterId: string | null;
      // Greeting picked on the empty-thread preview (0 is firstMessage, i is alternateGreetings[i-1]); thread-list seeds branches from it.
  greetingIndex: number;
};

const INITIAL_RUNTIME_STATE: ChatRuntimeState = {
  convId: null,
  historyLoaded: false,
  settingsOpen: false,
  lastStreamError: null,
  speakingCharacterId: null,
  greetingIndex: 0,
};

const chatRuntimeAtom = atom<ChatRuntimeState>(INITIAL_RUNTIME_STATE);

    // One read/write derived atom per field, backed by chatRuntimeAtom; call sites keep the same per-field API.
function runtimeField<K extends keyof ChatRuntimeState>(key: K) {
  return atom(
    (get) => get(chatRuntimeAtom)[key],
    (get, set, value: ChatRuntimeState[K]) => {
      set(chatRuntimeAtom, { ...get(chatRuntimeAtom), [key]: value });
    },
  );
}

export const convIdAtom = runtimeField("convId");
export const historyLoadedAtom = runtimeField("historyLoaded");
export const conversationSettingsOpenAtom = runtimeField("settingsOpen");
export const lastStreamErrorAtom = runtimeField("lastStreamError");
export const speakingCharacterIdAtom = runtimeField("speakingCharacterId");
export const greetingIndexAtom = runtimeField("greetingIndex");

export const chatHelpersAtom = atom<ChatHelpersRef | null>(null);

    // Per-user global macro vars (JSON map). localStorage-backed (outgrows the cookie cap); read into chatContext, updated from finish-meta.
export const globalVarsAtom = atomWithStorage<string>(
  "rp-global-vars",
  "{}",
  undefined,
  { getOnInit: true },
);

    // Authoritative local-DB owner (user id or GUEST_USER_ID). Server-seeded by UserIdProvider so it's correct on first render. Read via useLocalUserId().
export const localUserIdAtom = atom<number>(GUEST_USER_ID);

// Non-React stream callbacks read via chatStore.get/set.
export const chatStore = createStore();

// Returns active convId, generating fresh when unset; shared across transport/history/init.
export function ensureConvId(): string {
  const id = chatStore.get(convIdAtom) ?? uid();
  chatStore.set(convIdAtom, id);
  return id;
}
