import { env } from "@/lib/config/env";

export const dynamic = "force-static";

// MPP (Machine Payment Protocol) scanners probe /openapi.json at the
// site root. The canonical OpenAPI spec is generated by @elysiajs/openapi
// at /api/openapi/json, so redirect there rather than duplicating.
export function GET() {
  return Response.redirect(
    `${env.siteOrigin}/api/openapi/json`,
    308,
  );
}
