// Generated by scripts/gen-icon-sets.ts from icon-map.ts. Do not edit.
import type { IconComponent } from "@/lib/config/icon-map";
import { ArrowDown as i0 } from "iconoir-react/regular";
import { ArrowDownRight as i1 } from "iconoir-react/regular";
import { ArrowLeft as i2 } from "iconoir-react/regular";
import { ArrowRight as i3 } from "iconoir-react/regular";
import { ArrowUp as i4 } from "iconoir-react/regular";
import { DataTransferBoth as i5 } from "iconoir-react/regular";
import { ArrowUpRight as i6 } from "iconoir-react/regular";
import { NavArrowDown as i7 } from "iconoir-react/regular";
import { NavArrowLeft as i8 } from "iconoir-react/regular";
import { NavArrowRight as i9 } from "iconoir-react/regular";
import { ArrowUnionVertical as i10 } from "iconoir-react/regular";
import { FastArrowLeft as i11 } from "iconoir-react/regular";
import { FastArrowRight as i12 } from "iconoir-react/regular";
import { ArrowSeparateVertical as i13 } from "iconoir-react/regular";
import { Activity as i14 } from "iconoir-react/regular";
import { Check as i15 } from "iconoir-react/regular";
import { WarningCircle as i16 } from "iconoir-react/regular";
import { CheckCircle as i17 } from "iconoir-react/regular";
import { HelpCircle as i18 } from "iconoir-react/regular";
import { XmarkCircle as i19 } from "iconoir-react/regular";
import { WarningTriangle as i20 } from "iconoir-react/regular";
import { Prohibition as i21 } from "iconoir-react/regular";
import { InfoCircle as i22 } from "iconoir-react/regular";
import { RefreshDouble as i23 } from "iconoir-react/regular";
import { Xmark as i24 } from "iconoir-react/regular";
import { StatsReport as i25 } from "iconoir-react/regular";
import { StatsUpSquare as i26 } from "iconoir-react/regular";
import { StatsUpSquare as i27 } from "iconoir-react/regular";
import { GraphDown as i28 } from "iconoir-react/regular";
import { GraphUp as i29 } from "iconoir-react/regular";
import { DashboardSpeed as i30 } from "iconoir-react/regular";
import { Bell as i31 } from "iconoir-react/regular";
import { OpenBook as i32 } from "iconoir-react/regular";
import { OpenBook as i33 } from "iconoir-react/regular";
import { Calendar as i34 } from "iconoir-react/regular";
import { PasteClipboard as i35 } from "iconoir-react/regular";
import { CloudXmark as i36 } from "iconoir-react/regular";
import { CloudUpload as i37 } from "iconoir-react/regular";
import { Clock as i38 } from "iconoir-react/regular";
import { Code as i39 } from "iconoir-react/regular";
import { Copy as i40 } from "iconoir-react/regular";
import { Cpu as i41 } from "iconoir-react/regular";
import { Database as i42 } from "iconoir-react/regular";
import { DiceFive as i43 } from "iconoir-react/regular";
import { Dollar as i44 } from "iconoir-react/regular";
import { Download as i45 } from "iconoir-react/regular";
import { MoreHoriz as i46 } from "iconoir-react/regular";
import { MoreVert as i47 } from "iconoir-react/regular";
import { Erase as i48 } from "iconoir-react/regular";
import { OpenNewWindow as i49 } from "iconoir-react/regular";
import { Eye as i50 } from "iconoir-react/regular";
import { EyeClosed as i51 } from "iconoir-react/regular";
import { Page as i52 } from "iconoir-react/regular";
import { Filter as i53 } from "iconoir-react/regular";
import { FilterListCircle as i54 } from "iconoir-react/regular";
import { Fingerprint as i55 } from "iconoir-react/regular";
import { Gift as i56 } from "iconoir-react/regular";
import { Github as i57 } from "iconoir-react/regular";
import { Globe as i58 } from "iconoir-react/regular";
import { ViewGrid as i59 } from "iconoir-react/regular";
import { Hashtag as i60 } from "iconoir-react/regular";
import { Heart as i61 } from "iconoir-react/regular";
import { Home as i62 } from "iconoir-react/regular";
import { MediaImage as i63 } from "iconoir-react/regular";
import { MediaImage as i64 } from "iconoir-react/regular";
import { Key as i65 } from "iconoir-react/regular";
import { Key as i66 } from "iconoir-react/regular";
import { Dashboard as i67 } from "iconoir-react/regular";
import { ViewGrid as i68 } from "iconoir-react/regular";
import { Link as i69 } from "iconoir-react/regular";
import { Lock as i70 } from "iconoir-react/regular";
import { LogIn as i71 } from "iconoir-react/regular";
import { LogOut as i72 } from "iconoir-react/regular";
import { Mail as i73 } from "iconoir-react/regular";
import { Menu as i74 } from "iconoir-react/regular";
import { ChatBubbleEmpty as i75 } from "iconoir-react/regular";
import { ChatLines as i76 } from "iconoir-react/regular";
import { Microphone as i77 } from "iconoir-react/regular";
import { Computer as i78 } from "iconoir-react/regular";
import { HalfMoon as i79 } from "iconoir-react/regular";
import { MusicDoubleNote as i80 } from "iconoir-react/regular";
import { Palette as i81 } from "iconoir-react/regular";
import { SidebarCollapse as i82 } from "iconoir-react/regular";
import { EditPencil as i83 } from "iconoir-react/regular";
import { DesignPencil as i84 } from "iconoir-react/regular";
import { Percentage as i85 } from "iconoir-react/regular";
import { Play as i86 } from "iconoir-react/regular";
import { Plus as i87 } from "iconoir-react/regular";
import { RefreshDouble as i88 } from "iconoir-react/regular";
import { Refresh as i89 } from "iconoir-react/regular";
import { Repeat as i90 } from "iconoir-react/regular";
import { Undo as i91 } from "iconoir-react/regular";
import { Redo as i92 } from "iconoir-react/regular";
import { RssFeed as i93 } from "iconoir-react/regular";
import { Search as i94 } from "iconoir-react/regular";
import { Send as i95 } from "iconoir-react/regular";
import { Server as i96 } from "iconoir-react/regular";
import { Settings as i97 } from "iconoir-react/regular";
import { Shield as i98 } from "iconoir-react/regular";
import { ShieldCheck as i99 } from "iconoir-react/regular";
import { Shuffle as i100 } from "iconoir-react/regular";
import { Sparks as i101 } from "iconoir-react/regular";
import { SunLight as i102 } from "iconoir-react/regular";
import { Label as i103 } from "iconoir-react/regular";
import { Terminal as i104 } from "iconoir-react/regular";
import { Trash as i105 } from "iconoir-react/regular";
import { Trophy as i106 } from "iconoir-react/regular";
import { Type as i107 } from "iconoir-react/regular";
import { Upload as i108 } from "iconoir-react/regular";
import { User as i109 } from "iconoir-react/regular";
import { UserPlus as i110 } from "iconoir-react/regular";
import { Group as i111 } from "iconoir-react/regular";
import { VideoCamera as i112 } from "iconoir-react/regular";
import { Wallet as i113 } from "iconoir-react/regular";
import { MagicWand as i114 } from "iconoir-react/regular";
import { Flash as i115 } from "iconoir-react/regular";
import { ViewGrid as i116 } from "iconoir-react/regular";
import { Expand as i117 } from "iconoir-react/regular";
import { Settings as i118 } from "iconoir-react/regular";
import { Trash as i119 } from "iconoir-react/regular";
import { Brain as i120 } from "iconoir-react/regular";
import { WifiOff as i121 } from "iconoir-react/regular";
import { XmarkCircle as i122 } from "iconoir-react/regular";
import { WarningCircle as i123 } from "iconoir-react/regular";
import { Page as i124 } from "iconoir-react/regular";
import { Square as i125 } from "iconoir-react/regular";
import { Wrench as i126 } from "iconoir-react/regular";
import { List as i127 } from "iconoir-react/regular";
import { PlusCircle as i128 } from "iconoir-react/regular";
import { CreditCard as i129 } from "iconoir-react/regular";

export const ICONS: Record<string, IconComponent> = {
  "arrow-down": i0,
  "arrow-down-right": i1,
  "arrow-left": i2,
  "arrow-right": i3,
  "arrow-up": i4,
  "arrow-up-down": i5,
  "arrow-up-right": i6,
  "chevron-down": i7,
  "chevron-left": i8,
  "chevron-right": i9,
  "chevrons-down-up": i10,
  "chevrons-left": i11,
  "chevrons-right": i12,
  "chevrons-up-down": i13,
  activity: i14,
  check: i15,
  "circle-alert": i16,
  "circle-check": i17,
  "circle-help": i18,
  "circle-x": i19,
  "triangle-alert": i20,
  "octagon-x": i21,
  info: i22,
  loader: i23,
  x: i24,
  "chart-bar": i25,
  "chart-column": i26,
  "chart-column-big": i27,
  "trending-down": i28,
  "trending-up": i29,
  gauge: i30,
  bell: i31,
  "book-open": i32,
  "book-text": i33,
  calendar: i34,
  "clipboard-copy": i35,
  "cloud-off": i36,
  "cloud-upload": i37,
  clock: i38,
  code: i39,
  copy: i40,
  cpu: i41,
  database: i42,
  dices: i43,
  "dollar-sign": i44,
  download: i45,
  ellipsis: i46,
  "ellipsis-vertical": i47,
  eraser: i48,
  "external-link": i49,
  eye: i50,
  "eye-off": i51,
  file: i52,
  filter: i53,
  "filter-x": i54,
  fingerprint: i55,
  gift: i56,
  github: i57,
  globe: i58,
  grid: i59,
  hash: i60,
  heart: i61,
  house: i62,
  image: i63,
  "image-down": i64,
  key: i65,
  "key-round": i66,
  "layout-dashboard": i67,
  "layout-grid": i68,
  link: i69,
  lock: i70,
  "log-in": i71,
  "log-out": i72,
  mail: i73,
  menu: i74,
  "message-circle": i75,
  "message-square": i76,
  mic: i77,
  monitor: i78,
  moon: i79,
  music: i80,
  paintbrush: i81,
  "panel-left": i82,
  pencil: i83,
  "pencil-ruler": i84,
  percent: i85,
  play: i86,
  plus: i87,
  "refresh-ccw": i88,
  "refresh-cw": i89,
  repeat: i90,
  "rotate-ccw": i91,
  "rotate-cw": i92,
  rss: i93,
  search: i94,
  send: i95,
  server: i96,
  settings: i97,
  shield: i98,
  "shield-check": i99,
  shuffle: i100,
  sparkles: i101,
  sun: i102,
  tag: i103,
  terminal: i104,
  trash: i105,
  trophy: i106,
  type: i107,
  upload: i108,
  user: i109,
  "user-plus": i110,
  users: i111,
  video: i112,
  wallet: i113,
  wand: i114,
  zap: i115,
  "grid-3x3": i116,
  "maximize-2": i117,
  "settings-2": i118,
  "trash-2": i119,
  brain: i120,
  "wifi-off": i121,
  "x-circle": i122,
  "alert-circle": i123,
  "file-text": i124,
  square: i125,
  wrench: i126,
  list: i127,
  "plus-circle": i128,
  "credit-card": i129,
};
