// Generated by scripts/gen-icon-sets.ts from icon-map.ts. Do not edit.
import type { IconComponent } from "@/lib/config/icon-map";
import { RiArrowDownLine as i0 } from "@remixicon/react";
import { RiArrowRightDownLine as i1 } from "@remixicon/react";
import { RiArrowLeftLine as i2 } from "@remixicon/react";
import { RiArrowLeftRightLine as i3 } from "@remixicon/react";
import { RiArrowRightLine as i4 } from "@remixicon/react";
import { RiArrowLeftRightLine as i5 } from "@remixicon/react";
import { RiArrowUpLine as i6 } from "@remixicon/react";
import { RiArrowUpDownLine as i7 } from "@remixicon/react";
import { RiArrowRightUpLine as i8 } from "@remixicon/react";
import { RiArrowDownSLine as i9 } from "@remixicon/react";
import { RiArrowLeftSLine as i10 } from "@remixicon/react";
import { RiArrowRightSLine as i11 } from "@remixicon/react";
import { RiContractUpDownLine as i12 } from "@remixicon/react";
import { RiArrowLeftDoubleLine as i13 } from "@remixicon/react";
import { RiArrowRightDoubleLine as i14 } from "@remixicon/react";
import { RiExpandUpDownLine as i15 } from "@remixicon/react";
import { RiPulseLine as i16 } from "@remixicon/react";
import { RiCheckLine as i17 } from "@remixicon/react";
import { RiErrorWarningLine as i18 } from "@remixicon/react";
import { RiCheckboxCircleLine as i19 } from "@remixicon/react";
import { RiQuestionLine as i20 } from "@remixicon/react";
import { RiCloseCircleLine as i21 } from "@remixicon/react";
import { RiAlertLine as i22 } from "@remixicon/react";
import { RiForbidLine as i23 } from "@remixicon/react";
import { RiInformationLine as i24 } from "@remixicon/react";
import { RiLoaderLine as i25 } from "@remixicon/react";
import { RiCloseLine as i26 } from "@remixicon/react";
import { RiBarChartHorizontalLine as i27 } from "@remixicon/react";
import { RiBarChartLine as i28 } from "@remixicon/react";
import { RiBarChart2Line as i29 } from "@remixicon/react";
import { RiPieChartLine as i30 } from "@remixicon/react";
import { RiStockLine as i31 } from "@remixicon/react";
import { RiLineChartLine as i32 } from "@remixicon/react";
import { RiDashboard3Line as i33 } from "@remixicon/react";
import { RiBellLine as i34 } from "@remixicon/react";
import { RiBookOpenLine as i35 } from "@remixicon/react";
import { RiBookOpenLine as i36 } from "@remixicon/react";
import { RiCalendarLine as i37 } from "@remixicon/react";
import { RiClipboardLine as i38 } from "@remixicon/react";
import { RiCloudOffLine as i39 } from "@remixicon/react";
import { RiUploadCloud2Line as i40 } from "@remixicon/react";
import { RiTimeLine as i41 } from "@remixicon/react";
import { RiCodeLine as i42 } from "@remixicon/react";
import { RiFileCopyLine as i43 } from "@remixicon/react";
import { RiCpuLine as i44 } from "@remixicon/react";
import { RiDatabaseLine as i45 } from "@remixicon/react";
import { RiDiceLine as i46 } from "@remixicon/react";
import { RiMoneyDollarCircleLine as i47 } from "@remixicon/react";
import { RiDownloadLine as i48 } from "@remixicon/react";
import { RiMoreLine as i49 } from "@remixicon/react";
import { RiMore2Line as i50 } from "@remixicon/react";
import { RiEraserLine as i51 } from "@remixicon/react";
import { RiExternalLinkLine as i52 } from "@remixicon/react";
import { RiEyeLine as i53 } from "@remixicon/react";
import { RiEyeOffLine as i54 } from "@remixicon/react";
import { RiFileLine as i55 } from "@remixicon/react";
import { RiFileUnknowLine as i56 } from "@remixicon/react";
import { RiFilterLine as i57 } from "@remixicon/react";
import { RiFilterOffLine as i58 } from "@remixicon/react";
import { RiFingerprintLine as i59 } from "@remixicon/react";
import { RiGiftLine as i60 } from "@remixicon/react";
import { RiGithubLine as i61 } from "@remixicon/react";
import { RiGlobeLine as i62 } from "@remixicon/react";
import { RiLayoutGridLine as i63 } from "@remixicon/react";
import { RiDraggable as i64 } from "@remixicon/react";
import { RiHashtag as i65 } from "@remixicon/react";
import { RiHeartLine as i66 } from "@remixicon/react";
import { RiHeartPulseLine as i67 } from "@remixicon/react";
import { RiHome4Line as i68 } from "@remixicon/react";
import { RiImageLine as i69 } from "@remixicon/react";
import { RiKeyLine as i70 } from "@remixicon/react";
import { RiKey2Line as i71 } from "@remixicon/react";
import { RiStackLine as i72 } from "@remixicon/react";
import { RiDashboardLine as i73 } from "@remixicon/react";
import { RiLayoutGridLine as i74 } from "@remixicon/react";
import { RiLink as i75 } from "@remixicon/react";
import { RiLockLine as i76 } from "@remixicon/react";
import { RiLoginBoxLine as i77 } from "@remixicon/react";
import { RiLogoutBoxLine as i78 } from "@remixicon/react";
import { RiMailLine as i79 } from "@remixicon/react";
import { RiMenuLine as i80 } from "@remixicon/react";
import { RiChat1Line as i81 } from "@remixicon/react";
import { RiChat4Line as i82 } from "@remixicon/react";
import { RiMicLine as i83 } from "@remixicon/react";
import { RiComputerLine as i84 } from "@remixicon/react";
import { RiMoonLine as i85 } from "@remixicon/react";
import { RiMusicLine as i86 } from "@remixicon/react";
import { RiNewspaperLine as i87 } from "@remixicon/react";
import { RiBrushLine as i88 } from "@remixicon/react";
import { RiLayoutLeftLine as i89 } from "@remixicon/react";
import { RiPencilLine as i90 } from "@remixicon/react";
import { RiPencilRulerLine as i91 } from "@remixicon/react";
import { RiPercentLine as i92 } from "@remixicon/react";
import { RiPlayLine as i93 } from "@remixicon/react";
import { RiAddLine as i94 } from "@remixicon/react";
import { RiShutDownLine as i95 } from "@remixicon/react";
import { RiShutDownLine as i96 } from "@remixicon/react";
import { RiResetLeftLine as i97 } from "@remixicon/react";
import { RiRefreshLine as i98 } from "@remixicon/react";
import { RiRepeatLine as i99 } from "@remixicon/react";
import { RiAnticlockwise2Line as i100 } from "@remixicon/react";
import { RiClockwise2Line as i101 } from "@remixicon/react";
import { RiRssLine as i102 } from "@remixicon/react";
import { RiFileList3Line as i103 } from "@remixicon/react";
import { RiSearchLine as i104 } from "@remixicon/react";
import { RiSendPlaneLine as i105 } from "@remixicon/react";
import { RiServerLine as i106 } from "@remixicon/react";
import { RiSettingsLine as i107 } from "@remixicon/react";
import { RiShieldLine as i108 } from "@remixicon/react";
import { RiShieldCheckLine as i109 } from "@remixicon/react";
import { RiShuffleLine as i110 } from "@remixicon/react";
import { RiEqualizerLine as i111 } from "@remixicon/react";
import { RiSparklingLine as i112 } from "@remixicon/react";
import { RiSunLine as i113 } from "@remixicon/react";
import { RiPriceTag3Line as i114 } from "@remixicon/react";
import { RiTerminalLine as i115 } from "@remixicon/react";
import { RiTicketLine as i116 } from "@remixicon/react";
import { RiDeleteBinLine as i117 } from "@remixicon/react";
import { RiTrophyLine as i118 } from "@remixicon/react";
import { RiText as i119 } from "@remixicon/react";
import { RiUploadLine as i120 } from "@remixicon/react";
import { RiUserLine as i121 } from "@remixicon/react";
import { RiUserAddLine as i122 } from "@remixicon/react";
import { RiGroupLine as i123 } from "@remixicon/react";
import { RiVideoLine as i124 } from "@remixicon/react";
import { RiWalletLine as i125 } from "@remixicon/react";
import { RiMagicLine as i126 } from "@remixicon/react";
import { RiFlashlightLine as i127 } from "@remixicon/react";
import { RiGridLine as i128 } from "@remixicon/react";
import { RiExpandDiagonalLine as i129 } from "@remixicon/react";
import { RiSettings2Line as i130 } from "@remixicon/react";
import { RiDeleteBin2Line as i131 } from "@remixicon/react";
import { RiBrainLine as i132 } from "@remixicon/react";
import { RiWifiOffLine as i133 } from "@remixicon/react";
import { RiCloseCircleLine as i134 } from "@remixicon/react";
import { RiErrorWarningLine as i135 } from "@remixicon/react";
import { RiFileTextLine as i136 } from "@remixicon/react";
import { RiSquareLine as i137 } from "@remixicon/react";
import { RiWrenchLine as i138 } from "@remixicon/react";
import { RiListUnordered as i139 } from "@remixicon/react";
import { RiAddCircleLine as i140 } from "@remixicon/react";
import { RiBankCardLine as i141 } from "@remixicon/react";

export const ICONS: Record<string, IconComponent> = {
  "arrow-down": i0,
  "arrow-down-right": i1,
  "arrow-left": i2,
  "arrow-left-right": i3,
  "arrow-right": i4,
  "arrow-right-left": i5,
  "arrow-up": i6,
  "arrow-up-down": i7,
  "arrow-up-right": i8,
  "chevron-down": i9,
  "chevron-left": i10,
  "chevron-right": i11,
  "chevrons-down-up": i12,
  "chevrons-left": i13,
  "chevrons-right": i14,
  "chevrons-up-down": i15,
  activity: i16,
  check: i17,
  "circle-alert": i18,
  "circle-check": i19,
  "circle-help": i20,
  "circle-x": i21,
  "triangle-alert": i22,
  "octagon-x": i23,
  info: i24,
  loader: i25,
  x: i26,
  "chart-bar": i27,
  "chart-column": i28,
  "chart-column-big": i29,
  "chart-pie": i30,
  "trending-down": i31,
  "trending-up": i32,
  gauge: i33,
  bell: i34,
  "book-open": i35,
  "book-text": i36,
  calendar: i37,
  "clipboard-copy": i38,
  "cloud-off": i39,
  "cloud-upload": i40,
  clock: i41,
  code: i42,
  copy: i43,
  cpu: i44,
  database: i45,
  dices: i46,
  "dollar-sign": i47,
  download: i48,
  ellipsis: i49,
  "ellipsis-vertical": i50,
  eraser: i51,
  "external-link": i52,
  eye: i53,
  "eye-off": i54,
  file: i55,
  "file-question": i56,
  filter: i57,
  "filter-x": i58,
  fingerprint: i59,
  gift: i60,
  github: i61,
  globe: i62,
  grid: i63,
  "grip-vertical": i64,
  hash: i65,
  heart: i66,
  "heart-pulse": i67,
  house: i68,
  image: i69,
  key: i70,
  "key-round": i71,
  layers: i72,
  "layout-dashboard": i73,
  "layout-grid": i74,
  link: i75,
  lock: i76,
  "log-in": i77,
  "log-out": i78,
  mail: i79,
  menu: i80,
  "message-circle": i81,
  "message-square": i82,
  mic: i83,
  monitor: i84,
  moon: i85,
  music: i86,
  newspaper: i87,
  paintbrush: i88,
  "panel-left": i89,
  pencil: i90,
  "pencil-ruler": i91,
  percent: i92,
  play: i93,
  plus: i94,
  power: i95,
  "power-off": i96,
  "refresh-ccw": i97,
  "refresh-cw": i98,
  repeat: i99,
  "rotate-ccw": i100,
  "rotate-cw": i101,
  rss: i102,
  "scroll-text": i103,
  search: i104,
  send: i105,
  server: i106,
  settings: i107,
  shield: i108,
  "shield-check": i109,
  shuffle: i110,
  "sliders-horizontal": i111,
  sparkles: i112,
  sun: i113,
  tag: i114,
  terminal: i115,
  ticket: i116,
  trash: i117,
  trophy: i118,
  type: i119,
  upload: i120,
  user: i121,
  "user-plus": i122,
  users: i123,
  video: i124,
  wallet: i125,
  wand: i126,
  zap: i127,
  "grid-3x3": i128,
  "maximize-2": i129,
  "settings-2": i130,
  "trash-2": i131,
  brain: i132,
  "wifi-off": i133,
  "x-circle": i134,
  "alert-circle": i135,
  "file-text": i136,
  square: i137,
  wrench: i138,
  list: i139,
  "plus-circle": i140,
  "credit-card": i141,
};
