// Emits one module per non-default icon library with static imports of every
// icon the map names for it, so switching libraries costs one chunk instead
// of one request per icon. Source of truth stays src/lib/config/icon-map.ts.
//   bun scripts/gen-icon-sets.ts
import { readFileSync, writeFileSync } from "node:fs";

const LIBS = ["tabler", "phosphor", "heroicons", "remix", "iconoir"] as const;
const src = readFileSync("src/lib/config/icon-map.ts", "utf8");
const body = src.slice(src.indexOf("export const ICON_MAP"));

type Entry = {
  name: string;
  lib: string;
  module: string;
  named: string | null;
};
const entries: Entry[] = [];
const entryRe = /^  "?([\w-]+)"?: \{([\s\S]*?)^  \},?$/gm;
let m: RegExpExecArray | null;
while ((m = entryRe.exec(body)) !== null) {
  const [, name, block] = m;
  for (const lib of LIBS) {
    const libRe = new RegExp(
      `${lib}: \\(\\) =>\\s*import\\("([^"]+)"\\)(?:\\.then\\(\\s*\\(m\\) => \\(\\{\\s*default: m\\.(\\w+),?\\s*\\}\\),?\\s*\\))?`,
    );
    const lm = libRe.exec(block);
    if (!lm) continue;
    entries.push({ name, lib, module: lm[1], named: lm[2] ?? null });
  }
}

for (const lib of LIBS) {
  const mine = entries.filter((e) => e.lib === lib);
  const imports = new Map<string, string>(); // local ident -> import line
  const rows: string[] = [];
  for (const e of mine) {
    const ident = `i${rows.length}`;
    if (e.named)
      imports.set(
        ident,
        `import { ${e.named} as ${ident} } from "${e.module}";`,
      );
    else imports.set(ident, `import ${ident} from "${e.module}";`);
    rows.push(`  "${e.name}": ${ident},`);
  }
  const out = [
    "// Generated by scripts/gen-icon-sets.ts from icon-map.ts. Do not edit.",
    'import type { IconComponent } from "@/lib/config/icon-map";',
    ...imports.values(),
    "",
    "export const ICONS: Record<string, IconComponent> = {",
    ...rows,
    "};",
    "",
  ].join("\n");
  writeFileSync(`src/lib/config/icon-sets/${lib}.ts`, out);
  console.log(lib, mine.length, "icons");
}
