export enum StoreId {
  DATA_TABLES_STORE = "DATA_TABLES_STORE",
}

export enum ModelTypeFilter {
  ALL = "all",
  TEXT = "text",
  IMAGE = "image",
  VIDEO = "video",
  AUDIO = "audio",
  EMBEDDING = "embedding",
}

export enum Vendor {
  OPENAI = "openai",
  ANTHROPIC = "anthropic",
  GOOGLE = "google",
  BAILIAN = "bailian",
  BYTEDANCE = "bytedance",
  DEEPSEEK = "deepseek",
  FLUX = "flux",
  KLING = "kling",
  META = "meta",
  MISTRAL = "mistral",
  COHERE = "cohere",
  XAI = "xai",
  X_AI = "x.ai",
  MOONSHOT = "moonshot",
  ZHIPU = "zhipu",
  STABILITY = "stability",
  ALIBABA = "alibaba",
  IFLOW = "iflow",
  KUAISHOU = "kuaishou",
  SAP = "sap ai core",
  VERTEX = "vertex",
  AIHUBMIX = "aihubmix",
  OPENCODE = "opencode zen",
  XUNFEI = "xunfei",
  XUNFEI_CN = "讯飞",
  ZHIPU_CN = "智谱",
  ZHIPU_AI_CODING = "zhipu ai coding plan",
  XIAOMI = "xiaomi",
  MINIMAX = "minimax",
  VIDU = "vidu",
  NVIDIA = "nvidia",
  TENCENT = "tencent",
  HUNYUAN = "hunyuan",
  BAIDU = "baidu",
  QIANFAN = "qianfan",
  LIQUID = "liquid",
  CODEIUM = "codeium",
  INCLUSIONAI = "inclusionai",
  LING = "ling",
  ARCEE = "arcee",
  GROQ = "groq",
  SDAIA = "sdaia",
  BAAI = "baai",
  IBM = "ibm",
  JETBRAINS = "jetbrains",
  SPEAKLEASH = "speakleash",
  PLLUM = "pllum",
  VILLANOVA = "villanova",
  INCEPTION = "inception",
  KINFRA = "kinfra",
  DEEPREINFORCE = "deepreinforce",
  MICROSOFT = "microsoft",
  DEEPGRAM = "deepgram",
  MYSHELL = "myshell",
  LEONARDO = "leonardo",
  LYKON = "lykon",
  THEDRUMMER = "thedrummer",
  PFNET = "preferred",
  NEXAGI = "nex agi",
  POOLSIDE = "poolside",
  DOTSSTUDIO = "dots studio",
  AMAZON = "amazon",
  MOONDREAM = "moondream",
  SLAI = "sl-ai",
  JINA = "jina",
  AISINGAPORE = "ai singapore",
  POLLINATIONS = "pollinations",
  STEPFUN = "stepfun",
  PERPLEXITY = "perplexity",
  KATANEMO = "katanemo",
  NAVYAI = "navyai",
  HCOMPANY = "h company",
  AIONLABS = "aion labs",
  SAO10K = "sao10k",
  STEELSKULL = "steelskull",
  BRUHZWATER = "bruhzwater",
  FALLENMERICK = "fallenmerick",
  THINKINGMACHINES = "thinking machines",
  MEGANOVA = "meganova",
  AGNES = "agnes ai",
  REQUESTY = "requesty",
  ELECTRONHUB = "electronhub",
  GRYPHE = "gryphe",
  ANTHRACITE = "anthracite",
  ALLENAI = "ai2",
  AI21 = "ai21 labs",
  NOUS = "nous research",
  VOIDAI = "voidai",
  VENICE = "venice",
  ZANITY = "zanity",
  DEEPL = "deepl",
  ELEVENLABS = "elevenlabs",
  SPEECHIFY = "speechify",
  ESSENTIALAI = "essential ai",
  INTERNLM = "internlm",
  SENSENOVA = "sensenova",
  MEITUAN = "meituan",
  SWISSAI = "swiss ai",
  EUROLLM = "eurollm",
  DICTA = "dicta",
  VOYAGE = "voyage",
  ABLITERATION = "abliteration",
  ORCAROUTER = "orcarouter",
  REGOLO = "regolo",
  SARVAM = "sarvam",
  TYPHOON = "typhoon",
  AIHORDE = "aihorde",
  RUNWARE = "runware",
  STEALTH = "stealth",
}

export enum OS {
  WINDOWS = "windows",
  MACOS = "macos",
  LINUX = "linux",
}

export const OS_VALUES = Object.values(OS);

export function isOS(value: string): value is OS {
  return OS_VALUES.some((os) => os === value);
}

export enum DataTableId {
  MODELS = "MODELS",
  TOKENS = "TOKENS",
  LOGS = "LOGS",
  MIDJOURNEY_LOGS = "MIDJOURNEY_LOGS",
  TASK_LOGS = "TASK_LOGS",
  AFFILIATE_INVITEES = "AFFILIATE_INVITEES",
  AFFILIATE_COMMISSIONS = "AFFILIATE_COMMISSIONS",
  BILLING_TOPUP_HISTORY = "BILLING_TOPUP_HISTORY",
  BILLING_SUBSCRIPTION_HISTORY = "BILLING_SUBSCRIPTION_HISTORY",
}
