export enum StoreId {
  DASHBOARD_STORE = "DASHBOARD_STORE",
  DATA_TABLES_STORE = "DATA_TABLES_STORE",
}

export enum DataTableId {
  TOKENS = "TOKENS",
  LOGS = "LOGS",
  AFFILIATE_INVITEES = "AFFILIATE_INVITEES",
  AFFILIATE_COMMISSIONS = "AFFILIATE_COMMISSIONS",
}
