// Single home for per-vendor branding. Adding a vendor: add the Vendor enum
// member, then ONE theme entry + ONE icon loader here (custom SVGs go in
// components/elements/brand/). Badge SVG maps stay server-side in
// server/ops/badge/lib/vendor-svgs.ts so they never enter client chunks.
import type { ComponentType } from "react";

import { Vendor } from "@/lib/types/enums";

export type VendorTheme = {
  bg: string;
  border: string;
  text: string;
  tagBg: string;
  tagBorder: string;
  primary?: string;
};

const VENDOR_THEMES: Record<string, VendorTheme> = {
  [Vendor.OPENAI]: {
    bg: "bg-green-500/5",
    border: "border-green-500/20",
    text: "text-green-700 dark:text-green-300",
    tagBg: "bg-green-500/10",
    tagBorder: "border-green-500/20",
    primary: "#10a37f",
  },
  [Vendor.ANTHROPIC]: {
    bg: "bg-orange-500/5",
    border: "border-orange-500/20",
    text: "text-orange-700 dark:text-orange-300",
    tagBg: "bg-orange-500/10",
    tagBorder: "border-orange-500/20",
    primary: "#d97757",
  },
  [Vendor.ARCEE]: {
    bg: "bg-teal-500/5",
    border: "border-teal-500/20",
    text: "text-teal-700 dark:text-teal-300",
    tagBg: "bg-teal-500/10",
    tagBorder: "border-teal-500/20",
    primary: "#008c8c",
  },
  [Vendor.GOOGLE]: {
    bg: "bg-blue-500/5",
    border: "border-blue-500/20",
    text: "text-blue-700 dark:text-blue-300",
    tagBg: "bg-blue-500/10",
    tagBorder: "border-blue-500/20",
    primary: "#4285f4",
  },
  [Vendor.ALIBABA]: {
    bg: "bg-yellow-500/5",
    border: "border-yellow-500/20",
    text: "text-yellow-700 dark:text-yellow-300",
    tagBg: "bg-yellow-500/10",
    tagBorder: "border-yellow-500/20",
    primary: "#ff9900",
  },
  [Vendor.BAILIAN]: {
    bg: "bg-orange-500/5",
    border: "border-orange-500/20",
    text: "text-orange-600 dark:text-orange-300",
    tagBg: "bg-orange-500/10",
    tagBorder: "border-orange-500/20",
    primary: "#f97316",
  },
  [Vendor.BYTEDANCE]: {
    bg: "bg-sky-500/5",
    border: "border-sky-500/20",
    text: "text-sky-700 dark:text-sky-300",
    tagBg: "bg-sky-500/10",
    tagBorder: "border-sky-500/20",
    primary: "#3b82f6",
  },
  [Vendor.DEEPSEEK]: {
    bg: "bg-blue-500/5",
    border: "border-blue-500/20",
    text: "text-blue-700 dark:text-blue-300",
    tagBg: "bg-blue-500/10",
    tagBorder: "border-blue-500/20",
    primary: "#4d6bfe",
  },
  [Vendor.FLUX]: {
    bg: "bg-fuchsia-500/5",
    border: "border-fuchsia-500/20",
    text: "text-fuchsia-700 dark:text-fuchsia-300",
    tagBg: "bg-fuchsia-500/10",
    tagBorder: "border-fuchsia-500/20",
    primary: "#d946ef",
  },
  [Vendor.KLING]: {
    bg: "bg-violet-500/5",
    border: "border-violet-500/20",
    text: "text-violet-700 dark:text-violet-300",
    tagBg: "bg-violet-500/10",
    tagBorder: "border-violet-500/20",
    primary: "#8b5cf6",
  },
  [Vendor.META]: {
    bg: "bg-sky-500/5",
    border: "border-sky-500/20",
    text: "text-sky-700 dark:text-sky-300",
    tagBg: "bg-sky-500/10",
    tagBorder: "border-sky-500/20",
    primary: "#1877f2",
  },
  [Vendor.MISTRAL]: {
    bg: "bg-amber-500/5",
    border: "border-amber-500/20",
    text: "text-amber-700 dark:text-amber-300",
    tagBg: "bg-amber-500/10",
    tagBorder: "border-amber-500/20",
    primary: "#ff7000",
  },
  [Vendor.COHERE]: {
    bg: "bg-rose-500/5",
    border: "border-rose-500/20",
    text: "text-rose-700 dark:text-rose-300",
    tagBg: "bg-rose-500/10",
    tagBorder: "border-rose-500/20",
    primary: "#fb923c",
  },
  [Vendor.XAI]: {
    bg: "bg-zinc-500/5",
    border: "border-zinc-500/20",
    text: "text-zinc-700 dark:text-zinc-300",
    tagBg: "bg-zinc-500/10",
    tagBorder: "border-zinc-500/20",
    primary: "#1f2937",
  },
  [Vendor.MOONSHOT]: {
    bg: "bg-indigo-500/5",
    border: "border-indigo-500/20",
    text: "text-indigo-700 dark:text-indigo-300",
    tagBg: "bg-indigo-500/10",
    tagBorder: "border-indigo-500/20",
    primary: "#ec4899",
  },
  [Vendor.ZHIPU]: {
    bg: "bg-cyan-500/5",
    border: "border-cyan-500/20",
    text: "text-cyan-700 dark:text-cyan-300",
    tagBg: "bg-cyan-500/10",
    tagBorder: "border-cyan-500/20",
    primary: "#06b6d4",
  },
  [Vendor.STABILITY]: {
    bg: "bg-purple-500/5",
    border: "border-purple-500/20",
    text: "text-purple-600 dark:text-purple-300",
    tagBg: "bg-purple-500/10",
    tagBorder: "border-purple-500/20",
    primary: "#a855f7",
  },
  [Vendor.XIAOMI]: {
    bg: "bg-orange-500/5",
    border: "border-orange-500/20",
    text: "text-orange-700 dark:text-orange-300",
    tagBg: "bg-orange-500/10",
    tagBorder: "border-orange-500/20",
    primary: "#ff6900",
  },
  [Vendor.MINIMAX]: {
    bg: "bg-violet-500/5",
    border: "border-violet-500/20",
    text: "text-violet-700 dark:text-violet-300",
    tagBg: "bg-violet-500/10",
    tagBorder: "border-violet-500/20",
    primary: "#a855f7",
  },
  [Vendor.VIDU]: {
    bg: "bg-indigo-500/5",
    border: "border-indigo-500/20",
    text: "text-indigo-700 dark:text-indigo-300",
    tagBg: "bg-indigo-500/10",
    tagBorder: "border-indigo-500/20",
    primary: "#6366f1",
  },
  [Vendor.NVIDIA]: {
    bg: "bg-lime-500/5",
    border: "border-lime-500/20",
    text: "text-lime-700 dark:text-lime-300",
    tagBg: "bg-lime-500/10",
    tagBorder: "border-lime-500/20",
    primary: "#76b900",
  },
  [Vendor.TENCENT]: {
    bg: "bg-blue-500/5",
    border: "border-blue-500/20",
    text: "text-blue-700 dark:text-blue-300",
    tagBg: "bg-blue-500/10",
    tagBorder: "border-blue-500/20",
    primary: "#22c55e",
  },
  [Vendor.HUNYUAN]: {
    bg: "bg-blue-500/5",
    border: "border-blue-500/20",
    text: "text-blue-700 dark:text-blue-300",
    tagBg: "bg-blue-500/10",
    tagBorder: "border-blue-500/20",
    primary: "#3b82f6",
  },
  [Vendor.BAIDU]: {
    bg: "bg-indigo-500/5",
    border: "border-indigo-500/20",
    text: "text-indigo-700 dark:text-indigo-300",
    tagBg: "bg-indigo-500/10",
    tagBorder: "border-indigo-500/20",
    primary: "#ef4444",
  },
  [Vendor.QIANFAN]: {
    bg: "bg-indigo-500/5",
    border: "border-indigo-500/20",
    text: "text-indigo-700 dark:text-indigo-300",
    tagBg: "bg-indigo-500/10",
    tagBorder: "border-indigo-500/20",
    primary: "#6366f1",
  },
  [Vendor.LIQUID]: {
    bg: "bg-slate-500/5",
    border: "border-slate-500/20",
    text: "text-slate-700 dark:text-slate-300",
    tagBg: "bg-slate-500/10",
    tagBorder: "border-slate-500/20",
    primary: "#64748b",
  },
  [Vendor.CODEIUM]: {
    bg: "bg-teal-500/5",
    border: "border-teal-500/20",
    text: "text-teal-700 dark:text-teal-300",
    tagBg: "bg-teal-500/10",
    tagBorder: "border-teal-500/20",
    primary: "#09b6a2",
  },
  [Vendor.INCLUSIONAI]: {
    bg: "bg-blue-500/5",
    border: "border-blue-500/20",
    text: "text-blue-600 dark:text-blue-300",
    tagBg: "bg-blue-500/10",
    tagBorder: "border-blue-500/20",
    primary: "#3b82f6",
  },
  [Vendor.LING]: {
    bg: "bg-blue-500/5",
    border: "border-blue-500/20",
    text: "text-blue-600 dark:text-blue-300",
    tagBg: "bg-blue-500/10",
    tagBorder: "border-blue-500/20",
    primary: "#3b82f6",
  },
  [Vendor.GROQ]: {
    bg: "bg-orange-500/5",
    border: "border-orange-500/20",
    text: "text-orange-700 dark:text-orange-300",
    tagBg: "bg-orange-500/10",
    tagBorder: "border-orange-500/20",
    primary: "#f55036",
  },
  [Vendor.SDAIA]: {
    bg: "bg-emerald-500/5",
    border: "border-emerald-500/20",
    text: "text-emerald-700 dark:text-emerald-300",
    tagBg: "bg-emerald-500/10",
    tagBorder: "border-emerald-500/20",
    primary: "#006c35",
  },
  [Vendor.BAAI]: {
    bg: "bg-indigo-500/5",
    border: "border-indigo-500/20",
    text: "text-indigo-700 dark:text-indigo-300",
    tagBg: "bg-indigo-500/10",
    tagBorder: "border-indigo-500/20",
    primary: "#4f46e5",
  },
  [Vendor.IBM]: {
    bg: "bg-blue-500/5",
    border: "border-blue-500/20",
    text: "text-blue-700 dark:text-blue-300",
    tagBg: "bg-blue-500/10",
    tagBorder: "border-blue-500/20",
    primary: "#1261fe",
  },
  [Vendor.JETBRAINS]: {
    bg: "bg-fuchsia-500/5",
    border: "border-fuchsia-500/20",
    text: "text-fuchsia-700 dark:text-fuchsia-300",
    tagBg: "bg-fuchsia-500/10",
    tagBorder: "border-fuchsia-500/20",
    primary: "#fe315b",
  },
  [Vendor.SPEAKLEASH]: {
    bg: "bg-red-500/5",
    border: "border-red-500/20",
    text: "text-red-700 dark:text-red-300",
    tagBg: "bg-red-500/10",
    tagBorder: "border-red-500/20",
    primary: "#dc2626",
  },
  [Vendor.PLLUM]: {
    bg: "bg-rose-500/5",
    border: "border-rose-500/20",
    text: "text-rose-700 dark:text-rose-300",
    tagBg: "bg-rose-500/10",
    tagBorder: "border-rose-500/20",
    primary: "#e11d48",
  },
  [Vendor.VILLANOVA]: {
    bg: "bg-sky-500/5",
    border: "border-sky-500/20",
    text: "text-sky-700 dark:text-sky-300",
    tagBg: "bg-sky-500/10",
    tagBorder: "border-sky-500/20",
    primary: "#0284c7",
  },
  [Vendor.INCEPTION]: {
    bg: "bg-violet-500/5",
    border: "border-violet-500/20",
    text: "text-violet-700 dark:text-violet-300",
    tagBg: "bg-violet-500/10",
    tagBorder: "border-violet-500/20",
    primary: "#7c3aed",
  },
  [Vendor.KINFRA]: {
    bg: "bg-teal-500/5",
    border: "border-teal-500/20",
    text: "text-teal-700 dark:text-teal-300",
    tagBg: "bg-teal-500/10",
    tagBorder: "border-teal-500/20",
    primary: "#0d9488",
  },
  [Vendor.DEEPREINFORCE]: {
    bg: "bg-lime-500/5",
    border: "border-lime-500/20",
    text: "text-lime-700 dark:text-lime-300",
    tagBg: "bg-lime-500/10",
    tagBorder: "border-lime-500/20",
    primary: "#65a30d",
  },
  [Vendor.MICROSOFT]: {
    bg: "bg-sky-500/5",
    border: "border-sky-500/20",
    text: "text-sky-700 dark:text-sky-300",
    tagBg: "bg-sky-500/10",
    tagBorder: "border-sky-500/20",
    primary: "#0078d4",
  },
  [Vendor.DEEPGRAM]: {
    bg: "bg-emerald-500/5",
    border: "border-emerald-500/20",
    text: "text-emerald-700 dark:text-emerald-300",
    tagBg: "bg-emerald-500/10",
    tagBorder: "border-emerald-500/20",
    primary: "#13ef93",
  },
  [Vendor.MYSHELL]: {
    bg: "bg-violet-500/5",
    border: "border-violet-500/20",
    text: "text-violet-700 dark:text-violet-300",
    tagBg: "bg-violet-500/10",
    tagBorder: "border-violet-500/20",
    primary: "#6c5ce7",
  },
  [Vendor.LEONARDO]: {
    bg: "bg-purple-500/5",
    border: "border-purple-500/20",
    text: "text-purple-700 dark:text-purple-300",
    tagBg: "bg-purple-500/10",
    tagBorder: "border-purple-500/20",
    primary: "#6c2bd9",
  },
  [Vendor.LYKON]: {
    bg: "bg-rose-500/5",
    border: "border-rose-500/20",
    text: "text-rose-700 dark:text-rose-300",
    tagBg: "bg-rose-500/10",
    tagBorder: "border-rose-500/20",
    primary: "#e11d48",
  },
  [Vendor.THEDRUMMER]: {
    bg: "bg-red-500/5",
    border: "border-red-500/20",
    text: "text-red-700 dark:text-red-300",
    tagBg: "bg-red-500/10",
    tagBorder: "border-red-500/20",
    primary: "#dc2626",
  },
  [Vendor.PFNET]: {
    bg: "bg-cyan-500/5",
    border: "border-cyan-500/20",
    text: "text-cyan-700 dark:text-cyan-300",
    tagBg: "bg-cyan-500/10",
    tagBorder: "border-cyan-500/20",
    primary: "#00a0e9",
  },
  [Vendor.NEXAGI]: {
    bg: "bg-indigo-500/5",
    border: "border-indigo-500/20",
    text: "text-indigo-700 dark:text-indigo-300",
    tagBg: "bg-indigo-500/10",
    tagBorder: "border-indigo-500/20",
    primary: "#6366f1",
  },
  [Vendor.POOLSIDE]: {
    bg: "bg-teal-500/5",
    border: "border-teal-500/20",
    text: "text-teal-700 dark:text-teal-300",
    tagBg: "bg-teal-500/10",
    tagBorder: "border-teal-500/20",
    primary: "#14b8a6",
  },
  [Vendor.DOTSSTUDIO]: {
    bg: "bg-rose-500/5",
    border: "border-rose-500/20",
    text: "text-rose-700 dark:text-rose-300",
    tagBg: "bg-rose-500/10",
    tagBorder: "border-rose-500/20",
    primary: "#ff2442",
  },
  [Vendor.JINA]: {
    bg: "bg-red-500/5",
    border: "border-red-500/20",
    text: "text-red-700 dark:text-red-300",
    tagBg: "bg-red-500/10",
    tagBorder: "border-red-500/20",
    primary: "#e9264b",
  },
  [Vendor.AISINGAPORE]: {
    bg: "bg-red-500/5",
    border: "border-red-500/20",
    text: "text-red-700 dark:text-red-300",
    tagBg: "bg-red-500/10",
    tagBorder: "border-red-500/20",
    primary: "#ed2939",
  },
  [Vendor.POLLINATIONS]: {
    bg: "bg-pink-500/5",
    border: "border-pink-500/20",
    text: "text-pink-700 dark:text-pink-300",
    tagBg: "bg-pink-500/10",
    tagBorder: "border-pink-500/20",
    primary: "#ec4899",
  },
  [Vendor.STEPFUN]: {
    bg: "bg-blue-500/5",
    border: "border-blue-500/20",
    text: "text-blue-700 dark:text-blue-300",
    tagBg: "bg-blue-500/10",
    tagBorder: "border-blue-500/20",
    primary: "#005bff",
  },
  [Vendor.KATANEMO]: {
    bg: "bg-teal-500/5",
    border: "border-teal-500/20",
    text: "text-teal-700 dark:text-teal-300",
    tagBg: "bg-teal-500/10",
    tagBorder: "border-teal-500/20",
    primary: "#0d9488",
  },
  [Vendor.NAVYAI]: {
    bg: "bg-indigo-500/5",
    border: "border-indigo-500/20",
    text: "text-indigo-700 dark:text-indigo-300",
    tagBg: "bg-indigo-500/10",
    tagBorder: "border-indigo-500/20",
    primary: "#1e3a8a",
  },
  [Vendor.ABLITERATION]: {
    bg: "bg-rose-500/5",
    border: "border-rose-500/20",
    text: "text-rose-700 dark:text-rose-300",
    tagBg: "bg-rose-500/10",
    tagBorder: "border-rose-500/20",
    primary: "#e11d48",
  },
  [Vendor.ORCAROUTER]: {
    bg: "bg-cyan-500/5",
    border: "border-cyan-500/20",
    text: "text-cyan-700 dark:text-cyan-300",
    tagBg: "bg-cyan-500/10",
    tagBorder: "border-cyan-500/20",
    primary: "#0891b2",
  },
  [Vendor.REGOLO]: {
    bg: "bg-emerald-500/5",
    border: "border-emerald-500/20",
    text: "text-emerald-700 dark:text-emerald-300",
    tagBg: "bg-emerald-500/10",
    tagBorder: "border-emerald-500/20",
    primary: "#58e388",
  },
  [Vendor.SARVAM]: {
    bg: "bg-orange-500/5",
    border: "border-orange-500/20",
    text: "text-orange-700 dark:text-orange-300",
    tagBg: "bg-orange-500/10",
    tagBorder: "border-orange-500/20",
    primary: "#ea580c",
  },
  [Vendor.TYPHOON]: {
    bg: "bg-sky-500/5",
    border: "border-sky-500/20",
    text: "text-sky-700 dark:text-sky-300",
    tagBg: "bg-sky-500/10",
    tagBorder: "border-sky-500/20",
    primary: "#0284c7",
  },
  [Vendor.AIHORDE]: {
    bg: "bg-rose-500/5",
    border: "border-rose-500/20",
    text: "text-rose-700 dark:text-rose-300",
    tagBg: "bg-rose-500/10",
    tagBorder: "border-rose-500/20",
    primary: "#e11d48",
  },
  [Vendor.RUNWARE]: {
    bg: "bg-lime-500/5",
    border: "border-lime-500/20",
    text: "text-lime-700 dark:text-lime-300",
    tagBg: "bg-lime-500/10",
    tagBorder: "border-lime-500/20",
    primary: "#afff9f",
  },
  [Vendor.SWISSAI]: {
    bg: "bg-red-500/5",
    border: "border-red-500/20",
    text: "text-red-700 dark:text-red-300",
    tagBg: "bg-red-500/10",
    tagBorder: "border-red-500/20",
    primary: "#dc2626",
  },
  [Vendor.HCOMPANY]: {
    bg: "bg-violet-500/5",
    border: "border-violet-500/20",
    text: "text-violet-700 dark:text-violet-300",
    tagBg: "bg-violet-500/10",
    tagBorder: "border-violet-500/20",
    primary: "#7c3aed",
  },
  [Vendor.AIONLABS]: {
    bg: "bg-sky-500/5",
    border: "border-sky-500/20",
    text: "text-sky-700 dark:text-sky-300",
    tagBg: "bg-sky-500/10",
    tagBorder: "border-sky-500/20",
    primary: "#0ea5e9",
  },
  [Vendor.SAO10K]: {
    bg: "bg-rose-500/5",
    border: "border-rose-500/20",
    text: "text-rose-700 dark:text-rose-300",
    tagBg: "bg-rose-500/10",
    tagBorder: "border-rose-500/20",
    primary: "#e11d48",
  },
  [Vendor.STEELSKULL]: {
    bg: "bg-slate-500/5",
    border: "border-slate-500/20",
    text: "text-slate-700 dark:text-slate-300",
    tagBg: "bg-slate-500/10",
    tagBorder: "border-slate-500/20",
    primary: "#475569",
  },
  [Vendor.BRUHZWATER]: {
    bg: "bg-cyan-500/5",
    border: "border-cyan-500/20",
    text: "text-cyan-700 dark:text-cyan-300",
    tagBg: "bg-cyan-500/10",
    tagBorder: "border-cyan-500/20",
    primary: "#0891b2",
  },
  [Vendor.FALLENMERICK]: {
    bg: "bg-purple-500/5",
    border: "border-purple-500/20",
    text: "text-purple-700 dark:text-purple-300",
    tagBg: "bg-purple-500/10",
    tagBorder: "border-purple-500/20",
    primary: "#9333ea",
  },
  [Vendor.THINKINGMACHINES]: {
    bg: "bg-slate-500/5",
    border: "border-slate-500/20",
    text: "text-slate-700 dark:text-slate-300",
    tagBg: "bg-slate-500/10",
    tagBorder: "border-slate-500/20",
    primary: "#334155",
  },
  [Vendor.MEGANOVA]: {
    bg: "bg-emerald-500/5",
    border: "border-emerald-500/20",
    text: "text-emerald-700 dark:text-emerald-300",
    tagBg: "bg-emerald-500/10",
    tagBorder: "border-emerald-500/20",
    primary: "#059669",
  },
  [Vendor.GRYPHE]: {
    bg: "bg-amber-500/5",
    border: "border-amber-500/20",
    text: "text-amber-700 dark:text-amber-300",
    tagBg: "bg-amber-500/10",
    tagBorder: "border-amber-500/20",
    primary: "#d97706",
  },
  [Vendor.ANTHRACITE]: {
    bg: "bg-zinc-500/5",
    border: "border-zinc-500/20",
    text: "text-zinc-700 dark:text-zinc-300",
    tagBg: "bg-zinc-500/10",
    tagBorder: "border-zinc-500/20",
    primary: "#3f3f46",
  },
  [Vendor.ALLENAI]: {
    bg: "bg-orange-500/5",
    border: "border-orange-500/20",
    text: "text-orange-700 dark:text-orange-300",
    tagBg: "bg-orange-500/10",
    tagBorder: "border-orange-500/20",
    primary: "#f0529c",
  },
  [Vendor.AI21]: {
    bg: "bg-red-500/5",
    border: "border-red-500/20",
    text: "text-red-700 dark:text-red-300",
    tagBg: "bg-red-500/10",
    tagBorder: "border-red-500/20",
    primary: "#e6320f",
  },
  [Vendor.NOUS]: {
    bg: "bg-stone-500/5",
    border: "border-stone-500/20",
    text: "text-stone-700 dark:text-stone-300",
    tagBg: "bg-stone-500/10",
    tagBorder: "border-stone-500/20",
    primary: "#57534e",
  },
  [Vendor.VOIDAI]: {
    bg: "bg-violet-500/5",
    border: "border-violet-500/20",
    text: "text-violet-700 dark:text-violet-300",
    tagBg: "bg-violet-500/10",
    tagBorder: "border-violet-500/20",
    primary: "#7c3aed",
  },
  [Vendor.ZANITY]: {
    bg: "bg-pink-500/5",
    border: "border-pink-500/20",
    text: "text-pink-700 dark:text-pink-300",
    tagBg: "bg-pink-500/10",
    tagBorder: "border-pink-500/20",
    primary: "#ec4899",
  },
  [Vendor.DEEPL]: {
    bg: "bg-blue-500/5",
    border: "border-blue-500/20",
    text: "text-blue-700 dark:text-blue-300",
    tagBg: "bg-blue-500/10",
    tagBorder: "border-blue-500/20",
    primary: "#0f2b46",
  },
  [Vendor.ELEVENLABS]: {
    bg: "bg-zinc-500/5",
    border: "border-zinc-500/20",
    text: "text-zinc-700 dark:text-zinc-300",
    tagBg: "bg-zinc-500/10",
    tagBorder: "border-zinc-500/20",
    primary: "#1a1a1a",
  },
  [Vendor.SPEECHIFY]: {
    bg: "bg-red-500/5",
    border: "border-red-500/20",
    text: "text-red-700 dark:text-red-300",
    tagBg: "bg-red-500/10",
    tagBorder: "border-red-500/20",
    primary: "#ef4444",
  },
  [Vendor.ESSENTIALAI]: {
    bg: "bg-teal-500/5",
    border: "border-teal-500/20",
    text: "text-teal-700 dark:text-teal-300",
    tagBg: "bg-teal-500/10",
    tagBorder: "border-teal-500/20",
    primary: "#14b8a6",
  },
  [Vendor.KUAISHOU]: {
    bg: "bg-orange-500/5",
    border: "border-orange-500/20",
    text: "text-orange-700 dark:text-orange-300",
    tagBg: "bg-orange-500/10",
    tagBorder: "border-orange-500/20",
    primary: "#ff6600",
  },
  [Vendor.INTERNLM]: {
    bg: "bg-sky-500/5",
    border: "border-sky-500/20",
    text: "text-sky-700 dark:text-sky-300",
    tagBg: "bg-sky-500/10",
    tagBorder: "border-sky-500/20",
    primary: "#0ea5e9",
  },
  [Vendor.SENSENOVA]: {
    bg: "bg-rose-500/5",
    border: "border-rose-500/20",
    text: "text-rose-700 dark:text-rose-300",
    tagBg: "bg-rose-500/10",
    tagBorder: "border-rose-500/20",
    primary: "#e11d48",
  },
  [Vendor.VOYAGE]: {
    bg: "bg-cyan-500/5",
    border: "border-cyan-500/20",
    text: "text-cyan-700 dark:text-cyan-300",
    tagBg: "bg-cyan-500/10",
    tagBorder: "border-cyan-500/20",
    primary: "#0891b2",
  },
  [Vendor.OPENCODE]: {
    bg: "bg-slate-500/5",
    border: "border-slate-500/20",
    text: "text-slate-700 dark:text-slate-300",
    tagBg: "bg-slate-500/10",
    tagBorder: "border-slate-500/20",
    primary: "#64748b",
  },
  [Vendor.VENICE]: {
    bg: "bg-red-500/5",
    border: "border-red-500/20",
    text: "text-red-700 dark:text-red-300",
    tagBg: "bg-red-500/10",
    tagBorder: "border-red-500/20",
    primary: "#dc2626",
  },
  [Vendor.AGNES]: {
    bg: "bg-violet-500/5",
    border: "border-violet-500/20",
    text: "text-violet-700 dark:text-violet-300",
    tagBg: "bg-violet-500/10",
    tagBorder: "border-violet-500/20",
    primary: "#7c3aed",
  },
  [Vendor.REQUESTY]: {
    bg: "bg-cyan-500/5",
    border: "border-cyan-500/20",
    text: "text-cyan-700 dark:text-cyan-300",
    tagBg: "bg-cyan-500/10",
    tagBorder: "border-cyan-500/20",
    primary: "#0891b2",
  },
  [Vendor.ELECTRONHUB]: {
    bg: "bg-amber-500/5",
    border: "border-amber-500/20",
    text: "text-amber-700 dark:text-amber-300",
    tagBg: "bg-amber-500/10",
    tagBorder: "border-amber-500/20",
    primary: "#d97706",
  },
};

export const DEFAULT_THEME: VendorTheme = {
  bg: "bg-muted/30",
  border: "border-border",
  text: "text-muted-foreground",
  tagBg: "bg-secondary",
  tagBorder: "border-border",
  primary: "#94a3b8",
};

export function getVendorTheme(vendor: string): VendorTheme {
  const normalized = vendor.toLowerCase();
  for (const [key, theme] of Object.entries(VENDOR_THEMES)) {
    if (normalized.includes(key)) return theme;
  }
  return DEFAULT_THEME;
}

export type IconComponent = ComponentType<{
  size?: number | string;
  className?: string;
}>;

export type IconLoader = () => Promise<{ default: IconComponent }>;

export const VENDOR_LOADERS: Partial<Record<Vendor, IconLoader>> = {
  [Vendor.ALIBABA]: () => import("@lobehub/icons/es/AlibabaCloud"),
  [Vendor.ARCEE]: () => import("@lobehub/icons/es/Arcee"),
  [Vendor.ANTHROPIC]: () => import("@lobehub/icons/es/Anthropic"),
  [Vendor.BAIDU]: () => import("@lobehub/icons/es/Baidu"),
  [Vendor.BAILIAN]: () => import("@lobehub/icons/es/Bailian"),
  [Vendor.BYTEDANCE]: () => import("@lobehub/icons/es/ByteDance"),
  [Vendor.COHERE]: () => import("@lobehub/icons/es/Cohere"),
  [Vendor.DEEPSEEK]: () => import("@lobehub/icons/es/DeepSeek"),
  [Vendor.FLUX]: () => import("@lobehub/icons/es/Flux"),
  [Vendor.GOOGLE]: () => import("@lobehub/icons/es/Google"),
  [Vendor.GROQ]: () => import("@lobehub/icons/es/Groq"),
  [Vendor.SDAIA]: () => import("@/components/elements/brand/sdaia-icon"),
  [Vendor.BAAI]: () => import("@lobehub/icons/es/BAAI"),
  [Vendor.IBM]: () => import("@lobehub/icons/es/IBM"),
  [Vendor.JETBRAINS]: () =>
    import("@/components/elements/brand/jetbrains-icon"),
  [Vendor.INCEPTION]: () => import("@lobehub/icons/es/Inception"),
  [Vendor.KINFRA]: () => import("@lobehub/icons/es/Tencent"),
  [Vendor.SPEAKLEASH]: () =>
    import("@/components/elements/brand/speakleash-icon"),
  [Vendor.PLLUM]: () => import("@/components/elements/brand/pllum-icon"),
  [Vendor.VILLANOVA]: () =>
    import("@/components/elements/brand/villanova-icon"),
  [Vendor.DEEPREINFORCE]: () =>
    import("@/components/elements/brand/deepreinforce-icon"),
  [Vendor.MICROSOFT]: () => import("@lobehub/icons/es/Microsoft"),
  [Vendor.MYSHELL]: () => import("@lobehub/icons/es/MyShell"),
  [Vendor.DEEPGRAM]: () => import("@/components/elements/brand/deepgram-icon"),
  [Vendor.LEONARDO]: () => import("@/components/elements/brand/leonardo-icon"),
  [Vendor.LYKON]: () => import("@/components/elements/brand/lykon-icon"),
  [Vendor.THEDRUMMER]: () =>
    import("@/components/elements/brand/thedrummer-icon"),
  [Vendor.PFNET]: () => import("@/components/elements/brand/pfnet-icon"),
  [Vendor.NEXAGI]: () => import("@/components/elements/brand/nexagi-icon"),
  [Vendor.POOLSIDE]: () => import("@/components/elements/brand/poolside-icon"),
  [Vendor.DOTSSTUDIO]: () =>
    import("@/components/elements/brand/dotsstudio-icon"),
  [Vendor.AISINGAPORE]: () =>
    import("@/components/elements/brand/aisingapore-icon"),
  [Vendor.POLLINATIONS]: () => import("@lobehub/icons/es/Pollinations"),
  [Vendor.NAVYAI]: () => import("@/components/elements/brand/navyai-icon"),
  [Vendor.ABLITERATION]: () =>
    import("@/components/elements/brand/abliteration-icon"),
  [Vendor.ORCAROUTER]: () =>
    import("@/components/elements/brand/orcarouter-icon"),
  [Vendor.REGOLO]: () => import("@/components/elements/brand/regolo-icon"),
  [Vendor.SARVAM]: () => import("@/components/elements/brand/sarvam-icon"),
  [Vendor.TYPHOON]: () => import("@/components/elements/brand/typhoon-icon"),
  [Vendor.AIHORDE]: () => import("@/components/elements/brand/aihorde-icon"),
  [Vendor.RUNWARE]: () => import("@/components/elements/brand/runware-icon"),
  [Vendor.HCOMPANY]: () => import("@/components/elements/brand/hcompany-icon"),
  [Vendor.AIONLABS]: () => import("@lobehub/icons/es/AionLabs"),
  [Vendor.SAO10K]: () => import("@/components/elements/brand/sao10k-icon"),
  [Vendor.STEELSKULL]: () =>
    import("@/components/elements/brand/steelskull-icon"),
  [Vendor.BRUHZWATER]: () =>
    import("@/components/elements/brand/bruhzwater-icon"),
  [Vendor.THINKINGMACHINES]: () =>
    import("@/components/elements/brand/thinkingmachines-icon"),
  [Vendor.MEGANOVA]: () => import("@/components/elements/brand/meganova-icon"),
  [Vendor.AGNES]: () => import("@/components/elements/brand/agnes-icon"),
  [Vendor.REQUESTY]: () => import("@/components/elements/brand/requesty-icon"),
  [Vendor.ELECTRONHUB]: () =>
    import("@/components/elements/brand/electronhub-icon"),
  [Vendor.AI21]: () => import("@lobehub/icons/es/Ai21"),
  [Vendor.ALLENAI]: () => import("@lobehub/icons/es/Ai2"),
  [Vendor.NOUS]: () => import("@lobehub/icons/es/NousResearch"),
  [Vendor.GRYPHE]: () => import("@/components/elements/brand/gryphe-icon"),
  [Vendor.ANTHRACITE]: () =>
    import("@/components/elements/brand/anthracite-icon"),
  [Vendor.STEPFUN]: () => import("@lobehub/icons/es/Stepfun"),
  [Vendor.HUNYUAN]: () => import("@lobehub/icons/es/Hunyuan"),
  [Vendor.INCLUSIONAI]: () => import("@lobehub/icons/es/AntGroup"),
  [Vendor.JINA]: () => import("@lobehub/icons/es/Jina"),
  [Vendor.KLING]: () => import("@lobehub/icons/es/Kling"),
  [Vendor.LING]: () => import("@lobehub/icons/es/AntGroup"),
  [Vendor.CODEIUM]: () => import("@lobehub/icons/es/Windsurf"),
  [Vendor.LIQUID]: () => import("@lobehub/icons/es/Liquid"),
  [Vendor.META]: () => import("@lobehub/icons/es/Meta"),
  [Vendor.MINIMAX]: () => import("@lobehub/icons/es/Minimax"),
  [Vendor.VIDU]: () => import("@lobehub/icons/es/Vidu"),
  [Vendor.MISTRAL]: () => import("@lobehub/icons/es/Mistral"),
  [Vendor.MOONSHOT]: () => import("@lobehub/icons/es/Moonshot"),
  [Vendor.NVIDIA]: () => import("@lobehub/icons/es/Nvidia"),
  [Vendor.OPENAI]: () => import("@lobehub/icons/es/OpenAI"),
  [Vendor.PERPLEXITY]: () => import("@lobehub/icons/es/Perplexity"),
  [Vendor.QIANFAN]: () => import("@lobehub/icons/es/Baidu"),
  [Vendor.STABILITY]: () => import("@lobehub/icons/es/Stability"),
  [Vendor.TENCENT]: () => import("@lobehub/icons/es/Tencent"),
  [Vendor.XAI]: () => import("@lobehub/icons/es/XAI"),
  [Vendor.X_AI]: () => import("@lobehub/icons/es/XAI"),
  [Vendor.XIAOMI]: () => import("@lobehub/icons/es/XiaomiMiMo"),
  [Vendor.ZHIPU]: () => import("@lobehub/icons/es/Zhipu"),
  [Vendor.DEEPL]: () => import("@lobehub/icons/es/DeepL"),
  [Vendor.ELEVENLABS]: () => import("@lobehub/icons/es/ElevenLabs"),
  [Vendor.VOIDAI]: () => import("@/components/elements/brand/voidai-icon"),
  [Vendor.VENICE]: () => import("@lobehub/icons/es/Venice"),
  [Vendor.ZANITY]: () => import("@/components/elements/brand/zanity-icon"),
  [Vendor.SPEECHIFY]: () =>
    import("@/components/elements/brand/speechify-icon"),
  [Vendor.ESSENTIALAI]: () => import("@lobehub/icons/es/EssentialAI"),
  [Vendor.KUAISHOU]: () => import("@lobehub/icons/es/Kwaipilot"),
  [Vendor.INTERNLM]: () => import("@lobehub/icons/es/InternLM"),
  [Vendor.SENSENOVA]: () => import("@lobehub/icons/es/SenseNova"),
  [Vendor.MEITUAN]: () => import("@lobehub/icons/es/LongCat"),
  [Vendor.SWISSAI]: () => import("@/components/elements/brand/swissai-icon"),
  [Vendor.EUROLLM]: () => import("@/components/elements/brand/eurollm-icon"),
  [Vendor.DICTA]: () => import("@/components/elements/brand/dicta-icon"),
  [Vendor.VOYAGE]: () => import("@lobehub/icons/es/Voyage"),
  [Vendor.OPENCODE]: () => import("@lobehub/icons/es/OpenCode"),
};

export const ALIAS_LOADERS: Record<string, IconLoader> = {
  alibabacloud: () => import("@lobehub/icons/es/AlibabaCloud"),
  claude: () => import("@lobehub/icons/es/Claude"),
  doubao: () => import("@lobehub/icons/es/Doubao"),
  gemini: () => import("@lobehub/icons/es/Gemini"),
  nemotron: () => import("@lobehub/icons/es/Nvidia"),
  horde: () => import("@/components/elements/brand/aihorde-icon"),
};
