name: Docker Prod

on:
  workflow_dispatch:
  push:
    branches: [main]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Create env file
        run: |
          echo NEXT_PUBLIC_APP_NAME=${{ secrets.NEXT_PUBLIC_APP_NAME }} > .env
          echo NEXT_PUBLIC_URL=${{ secrets.NEXT_PUBLIC_URL }} >> .env
          echo NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }} >> .env
          echo NEXT_PUBLIC_SUPPORT_EMAIL=${{ secrets.NEXT_PUBLIC_SUPPORT_EMAIL }} >> .env
          echo NEXT_PUBLIC_GITHUB_URL=${{ secrets.NEXT_PUBLIC_GITHUB_URL }} >> .env
          echo NEXT_PUBLIC_DISCORD_URL=${{ secrets.NEXT_PUBLIC_DISCORD_URL }} >> .env
          echo NEXT_PUBLIC_TWITTER_HANDLE=${{ secrets.NEXT_PUBLIC_TWITTER_HANDLE }} >> .env

          echo SYSTEM_ACCESS_TOKEN=${{ secrets.SYSTEM_ACCESS_TOKEN }} >> .env

          echo TURSO_DATABASE_URL=${{ secrets.TURSO_DATABASE_URL }} >> .env
          echo TURSO_AUTH_TOKEN=${{ secrets.TURSO_AUTH_TOKEN }} >> .env

          echo R2_ACCOUNT_ID=${{ secrets.R2_ACCOUNT_ID }} >> .env
          echo R2_ACCESS_KEY_ID=${{ secrets.R2_ACCESS_KEY_ID }} >> .env
          echo R2_SECRET_ACCESS_KEY=${{ secrets.R2_SECRET_ACCESS_KEY }} >> .env
          echo R2_PUBLIC_URL=${{ secrets.R2_PUBLIC_URL }} >> .env
          echo R2_BUCKET=${{ secrets.R2_BUCKET }} >> .env

          echo TAVILY_API_KEY=${{ secrets.TAVILY_API_KEY }} >> .env

          echo GUEST_API_KEY=${{ secrets.GUEST_API_KEY }} >> .env

          echo NEXT_PUBLIC_POSTHOG_KEY=${{ secrets.NEXT_PUBLIC_POSTHOG_KEY }} >> .env
          echo NEXT_PUBLIC_POSTHOG_HOST=${{ secrets.NEXT_PUBLIC_POSTHOG_HOST }} >> .env
          echo POSTHOG_PROXY_HOST=${{ secrets.POSTHOG_PROXY_HOST }} >> .env
          echo POSTHOG_API_KEY=${{ secrets.POSTHOG_API_KEY }} >> .env
          echo POSTHOG_ENV_ID=${{ secrets.POSTHOG_ENV_ID }} >> .env

      - name: Docker run
        run: docker compose up -d --force-recreate --build
